### ISSUE TITLE
tests/json package conflicts with python's standard lib json

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#1002]
When running tests as standalone scripts, `$DSS_HOME/tests` is in `sys.path`. This causes the package `tests/json` to conflict with the standard library `json`.

```
(data-store) MacBook-Pro(master)>python tests/test_file.py 
Traceback (most recent call last):
  File "tests/test_file.py", line 17, in <module>
    import dss
  File "/Users/xath/Dropbox/ucsc_genomics_institute/code/repos/data-store/dss/__init__.py", line 13, in <module>
    import connexion.apis.abstract
  File "/Users/xath/.virtualenvs/data-store/lib/python3.6/site-packages/connexion/__init__.py", line 3, in <module>
    from .apis import AbstractAPI  # NOQA
  File "/Users/xath/.virtualenvs/data-store/lib/python3.6/site-packages/connexion/apis/__init__.py", line 1, in <module>
    from .abstract import AbstractAPI  # NOQA
  File "/Users/xath/.virtualenvs/data-store/lib/python3.6/site-packages/connexion/apis/abstract.py", line 8, in <module>
    import jinja2
  File "/Users/xath/.virtualenvs/data-store/lib/python3.6/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/Users/xath/.virtualenvs/data-store/lib/python3.6/site-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/Users/xath/.virtualenvs/data-store/lib/python3.6/site-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/Users/xath/.virtualenvs/data-store/lib/python3.6/site-packages/jinja2/utils.py", line 41, in <module>
    _slash_escape = '\\/' not in json.dumps('/')
AttributeError: module 'json' has no attribute 'dumps'
```

**Comment by hannes-ucsc** [comment]
Possible fixes:

- remove shebang from each test script, essentially removing the ability to invoke it directly (you'd have to run it via Makefile or using `python -m tests.test_foo`

- separate the test scripts from the `tests` package

- rename `json`,  but this conflict could occur again with other packages (both from dependencies and standard library)

- remove the `tests` dir from sys.path as part of the import hack that's already there

**Comment by kislyuk** [comment]
I vote for not having naming conflicts with the standard library or our dependencies in our tests directory. Let's rename `json` to something more specific.
