### ISSUE TITLE
tests/test_hcagenerator.py fails sporadically

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#1003]
https://travis-ci.org/HumanCellAtlas/data-store/jobs/344596146#L835

```
ERROR: test_generation (__main__.TestHCAGenerator) [analysis_bundle.json]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_hcagenerator.py", line 38, in test_generation
    fake_json = self.faker.generate(name)
  File "/home/travis/build/HumanCellAtlas/data-store/tests/json/hca_generator.py", line 41, in generate
    return json.dumps(generated_json)
  File "/opt/python/3.6.3/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/opt/python/3.6.3/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/python/3.6.3/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/python/3.6.3/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Decimal' is not JSON serializable
```

I propose that the main JSON generation function/method always validates the generated JSON before returning it. This might make diagnosis of bugs *like* this one easier.

I was able to reproduce this locally with 100 repetitions of that test. Some failures mentioned `Decimal`, others mentioned `datetime`.

**Comment by hannes-ucsc** [comment]
https://travis-ci.org/HumanCellAtlas/data-store/jobs/344681001#L970

**Comment by hannes-ucsc** [comment]
I restarted that Travis job so the above link isn't valid anymore.
