### ISSUE TITLE
Smoketest consistently fails with AccessDenied in PUT /files

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#1004]
https://travis-ci.org/HumanCellAtlas/data-store/builds/344701248#L1136

```
Traceback (most recent call last):
  File "/home/travis/build/HumanCellAtlas/data-store/smoketest-g4dlzk2g.tmp/venv/bin/hca", line 13, in <module>
    cli.main()
  File "/home/travis/build/HumanCellAtlas/data-store/smoketest-g4dlzk2g.tmp/venv/lib/python3.6/site-packages/hca/cli.py", line 65, in main
    result = parsed_args.entry_point(parsed_args)
  File "/home/travis/build/HumanCellAtlas/data-store/smoketest-g4dlzk2g.tmp/venv/lib/python3.6/site-packages/hca/util/__init__.py", line 392, in arg_forwarder
    return command(**command_args)
  File "/home/travis/build/HumanCellAtlas/data-store/smoketest-g4dlzk2g.tmp/venv/lib/python3.6/site-packages/hca/dss/__init__.py", line 95, in upload
    source_url=source_url
  File "/home/travis/build/HumanCellAtlas/data-store/smoketest-g4dlzk2g.tmp/venv/lib/python3.6/site-packages/hca/util/__init__.py", line 132, in _request
    raise SwaggerAPIException(response=res)
hca.util.exceptions.SwaggerAPIException: unhandled_exception: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied (HTTP 500). Details:
Traceback (most recent call last):
  File "/var/task/chalicelib/dss/error.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/var/task/chalicelib/dss/api/files.py", line 209, in put
    write_file_metadata(handle, dst_bucket, uuid, version, file_metadata_json)
  File "/var/task/chalicelib/dss/api/files.py", line 249, in write_file_metadata
    io.BytesIO(document.encode("utf-8")))
  File "/var/task/cloud_blobstore/s3.py", line 161, in upload_file_handle
    Key=key,
  File "/var/task/boto3/s3/inject.py", line 431, in upload_fileobj
    return future.result()
  File "/var/task/s3transfer/futures.py", line 73, in result
    return self._coordinator.result()
  File "/var/task/s3transfer/futures.py", line 233, in result
    raise self._exception
  File "/var/task/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/var/task/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/var/task/s3transfer/upload.py", line 679, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/var/task/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
```

**Comment by xbrianh** [comment]
The dss-dev IAM role was corrupted by a stray deploy. Hot patched role via AWS console and fixed.
