### ISSUE TITLE
Indexer logs alarming exception on blob creation events

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#1069]
Note that the level is WARNING. We should catch the blob case in `ObjectIdentier.from_key` and log an info message w/o stacktrace.

```
[WARNING]    2018-03-20T17:40:40.532Z    ce9f37e5-2c65-11e8-9e9c-f54d9f084bc1    An exception occurred in retry.TX(name='index_object', {'key': 'blobs/51449b4dc6a06308fc1637d0a641c589eeaef0c59944174f3b28bc2cfa0ea65c.e6a3982eac3fc0ff114e95463a9015e460214057.0346af3a8684f233600388447062bb70-2.d2360013', 'indexer': AWSIndexer(dryrun=False, notify=True)}).
Traceback (most recent call last):
  File "/var/task/domovoilib/dss/util/retry.py", line 207, in wrapper
    return f(*args, **kwargs)
  File "/var/task/domovoilib/dss/events/handlers/index.py", line 48, in index_object
    identifier = ObjectIdentifier.from_key(key)
  File "/var/task/domovoilib/dss/storage/identifiers.py", line 49, in from_key
    raise ObjectIdentifierError(f"Key does not represent a valid identifier: {key}")
dss.storage.identifiers.ObjectIdentifierError: Key does not represent a valid identifier: blobs/51449b4dc6a06308fc1637d0a641c589eeaef0c59944174f3b28bc2cfa0ea65c.e6a3982eac3fc0ff114e95463a9015e460214057.0346af3a8684f233600388447062bb70-2.d2360013
Stack (most recent call last):
  File "/var/runtime/awslambda/bootstrap.py", line 538, in <module>
    main()
  File "/var/runtime/awslambda/bootstrap.py", line 533, in main
    handle_event_request(request_handler, invokeid, event_body, context_objs, invoked_function_arn)
  File "/var/runtime/awslambda/bootstrap.py", line 250, in handle_event_request
    result = request_handler(json_input, context)
  File "/var/task/domovoi/app.py", line 127, in __call__
    result = handler(event, context)
  File "/var/task/app.py", line 30, in dispatch_s3_indexer_event
    indexer.process_new_indexable_object(event)
  File "/var/task/domovoilib/dss/events/handlers/index.py", line 36, in process_new_indexable_object
    self.index_object(key)
  File "/var/task/domovoilib/dss/util/retry.py", line 209, in wrapper
    tx.log_exception(e)
  File "/var/task/domovoilib/dss/util/retry.py", line 282, in log_exception
    self.logger.warning("An exception occurred in %r.", self, exc_info=True, stack_info=True)
None
END RequestId: ce9f37e5-2c65-11e8-9e9c-f54d9f084bc1
```

**Comment by hannes-ucsc** [comment]
This is old code on staging. Master does not exhibit this behavior.
