### ISSUE TITLE
PUT /files returns 404 even after file was created

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#1070]
Reported by @rolando-ebi on Slack.

```
RESPONSE:
500
Content-Type: application/problem+json
Content-Length: 1494
Connection: keep-alive
Date: Tue, 20 Mar 2018 17:24:57 GMT
x-amzn-RequestId: 9c01866e-2c63-11e8-93a1-f9f85bb14d02
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
X-Amzn-Trace-Id: sampled=1;root=1-5ab143e8-b569cf6b1bd5b7ae1a5d48a4
X-Cache: Error from cloudfront
Via: 1.1 b616547b82b9dbf8ee8fa60106de4b1c.cloudfront.net (CloudFront)
X-Amz-Cf-Id: mKGQTWE913LZQv9Ra3kcu2LlqjQ8VVNwwHSJKNjjLy3Cu7Hy6j16fQ==

{
  "code": "unhandled_exception",
  "stacktrace": "Traceback (most recent call last):\n  File \"/var/task/cloud_blobstore/s3.py\", line 211, in get_all_metadata\n    Key=key\n  File \"/var/task/botocore/client.py\", line 314, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/var/task/botocore/client.py\", line 612, in _make_api_call\n    raise error_class(parsed_response, operation_name)\nbotocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/var/task/chalicelib/dss/error.py\", line 26, in wrapper\n    return func(*args, **kwargs)\n  File \"/var/task/chalicelib/dss/api/files.py\", line 206, in put\n    assert hca_handle.verify_blob_checksum(dst_bucket, dst_key, metadata)\n  File \"/var/task/chalicelib/dss/storage/hcablobstore/s3.py\", line 22, in verify_blob_checksum\n    checksum = self.handle.get_cloud_checksum(bucket, key)\n  File \"/var/task/cloud_blobstore/s3.py\", line 245, in get_cloud_checksum\n    response = self.get_all_metadata(bucket, key)\n  File \"/var/task/cloud_blobstore/s3.py\", line 216, in get_all_metadata\n    raise BlobNotFoundError(ex)\ncloud_blobstore.BlobNotFoundError: An error occurred (404) when calling the HeadObject operation: Not Found\n",
  "status": 500,
  "title": "An error occurred (404) when calling the HeadObject operation: Not Found"
}

REQUEST:
PUT https://dss.dev.data.humancellatlas.org/v1/files/8dba762b-a12d-48fb-a3fb-df8c94a25fd0
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.18.4
Content-type: application/json
Content-Length: 192

{"creator_uid": 8008, "bundle_uuid": "070361fd-a0ee-463f-bd48-bf650a5a46cc", "source_url": "s3://org-humancellatlas-upload-dev/c4cfaf20-c786-42ed-9127-0d89eafb338a/biomaterial_bundle_46.json"}
```

**Comment by hannes-ucsc** [comment]
@rolando-ebi could post a link to the the portion of your code where this ocurred. I'm looking for proof that the staged object was indeed successfully created which would indicate that this is a race caused by S3's eventual consistency.

**Comment by rolando-ebi** [comment]
@hannes-ucsc Thanks for looking into this https://github.com/HumanCellAtlas/ingest-broker/blob/master/broker/dssapi.py#L51

**Comment by kislyuk** [comment]
The eventual consistency hypothesis doesn't make sense. S3 provides read-after-write consistency for new objects. https://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#ConsistencyModel

**Comment by hannes-ucsc** [comment]
Did you see the caveat on that page:

> The caveat is that if you make a HEAD or GET request to the key name (to find if the object exists) before creating the object, Amazon S3 provides eventual consistency for read-after-write.

**Comment by kislyuk** [comment]
I think you are right. There may not be a good way to provide consistency in this situation.

**Comment by kislyuk** [comment]
Since we have microsecond resolution, I think it might be preferable to eat the possibility of collisions and remove the existence check in https://github.com/HumanCellAtlas/data-store/blob/master/dss/api/files.py#L238-L249, and get read-after-write consistency in exchange. @ttung interest

**Comment by hannes-ucsc** [comment]
I agree that the existence check you point at could also trigger eventually consistent reads, but for the object in the storage bucket. This 404 is for the staged file in the staging bucket, I think. So the GET/HEAD-before-PUT must be somewhere else. The upload code in the CLI maybe? @sampierson?

**Comment by hannes-ucsc** [comment]
This is the unJSONed server-side backtrace 
```
Traceback (most recent call last):
  File "/var/task/cloud_blobstore/s3.py", line 211, in get_all_metadata
    Key=key
  File "/var/task/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/chalicelib/dss/error.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/var/task/chalicelib/dss/api/files.py", line 206, in put
    assert hca_handle.verify_blob_checksum(dst_bucket, dst_key, metadata)
  File "/var/task/chalicelib/dss/storage/hcablobstore/s3.py", line 22, in verify_blob_checksum
    checksum = self.handle.get_cloud_checksum(bucket, key)
  File "/var/task/cloud_blobstore/s3.py", line 245, in get_cloud_checksum
    response = self.get_all_metadata(bucket, key)
  File "/var/task/cloud_blobstore/s3.py", line 216, in get_all_metadata
    raise BlobNotFoundError(ex)
cloud_blobstore.BlobNotFoundError: An error occurred (404) when calling the HeadObject operation: Not Found
```

**Comment by hannes-ucsc** [comment]
I was [wrong)[https://github.com/HumanCellAtlas/data-store/issues/1070#issuecomment-375036040] about the object on which the HEAD occurs. This is all about the destination object, not the staged source object. The HEAD from line 156 precedes the PUT in line 203 (and I'm assuming .copy() involves PUT) which then causes the HEAD in line 206 to fail.

**Comment by kozbo** [comment]
Possibly another instance from Rolando:
```2018-03-27 15:47:33,679  - ingestbroker.broker.dssapi - ERROR in dssapi.py:194 _retry_when_http_error(): 
Response was: 500 ({
  "code": "unhandled_exception",
  "stacktrace": "Traceback (most recent call last):\n  File \"/var/task/cloud_blobstore/s3.py\", line 211, in get_all_metadata\n    Key=key\n  File \"/var/task/botocore/client.py\", line 314, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/var/task/botocore/client.py\", line 612, in _make_api_call\n    raise error_class(parsed_response, operation_name)\nbotocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/var/task/chalicelib/dss/error.py\", line 26, in wrapper\n    return func(*args, **kwargs)\n  File \"/var/task/chalicelib/dss/api/files.py\", line 133, in put\n    metadata = handle.get_user_metadata(src_bucket, src_key)\n  File \"/var/task/cloud_blobstore/s3.py\", line 263, in get_user_metadata\n    response = self.get_all_metadata(bucket, key)\n  File \"/var/task/cloud_blobstore/s3.py\", line 217, in get_all_metadata\n    raise BlobStoreUnknownError(ex)\ncloud_blobstore.BlobStoreUnknownError: An error occurred (403) when calling the HeadObject operation: Forbidden\n",
  "status": 500,
  "title": "An error occurred (403) when calling the HeadObject operation: Forbidden"
}
)```

**Comment by kozbo** [comment]
Reopen if this happens again. Please provide evidence
