### ISSUE TITLE
Non determinism in test_jsongenerator

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#1071]
```
coverage run -p --source=dss tests/test_jsongenerator.py -v
ok
test_file_put_large (__main__.TestFileApi) ... skipped 'Skipping integration test'
test_file_put_metadata_from_tags (__main__.TestFileApi) ... test_additionalItems (__main__.TestArray) ... ok
test_common (__main__.TestArray) ... ok
test_file_put_upper_case_checksums (__main__.TestFileApi) ... ok
test_constants (__main__.TestArray) ... ok
test_contains (__main__.TestArray) ... ok
test_enums (__main__.TestArray) ... ok
test_in_range (__main__.TestArray) ... ok
test_items_is_array (__main__.TestArray) ... ok
test_items_is_schema (__main__.TestArray) ... ok
test_unique (__main__.TestArray) ... ok
test_unique_enums (__main__.TestArray) ... ok
test_common (__main__.TestInteger) ... ok
test_exclusive_range (__main__.TestInteger)
does not exceed exclusive range ... ok
test_inclusive_range (__main__.TestInteger) ... ok
test_multiple_of (__main__.TestInteger) ... ok
test_multiple_of_in_range (__main__.TestInteger)
is a multiple of and within boundaries ... ok
test_generate (__main__.TestJsonGenerator) ... ok
test_file_size (__main__.TestFileApi) ... ok
test_common (__main__.TestNumber) ... ok
test_exclusive_range (__main__.TestNumber) ... ok
test_inclusive_range (__main__.TestNumber) ... test_multiple_of (__main__.TestNumber) ... ok
test_multiple_of_in_inclusive_range (__main__.TestNumber) ... ok
test_additionalProperties (__main__.TestObject) ... ok
test_dependencies (__main__.TestObject) ... ok
test_patternProperties (__main__.TestObject) ... ok
test_properties (__main__.TestObject) ... ok
test_propertyNames (__main__.TestObject) ... ok
test_range (__main__.TestObject) ... ok
test_required (__main__.TestObject) ... ok
test_common (__main__.TestString) ... ok
test_maxLength (__main__.TestString)
does not exceed maxLength ... ok
test_minLength (__main__.TestString)
does not exceed minLength ... ok
test_minimum_is_maximum (__main__.TestString)
minLength == maxLength ... ok
test_pattern (__main__.TestString) ... ok
test_pattern_within_range (__main__.TestString)
WIP matches pattern and does not exceed minLength or maxLength ... ok
test_range (__main__.TestString)
does not exceed maxLength or minLength ... ok
======================================================================
FAIL: test_inclusive_range (__main__.TestNumber) [does not exceed minimum of 0.1]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_jsongenerator.py", line 257, in test_inclusive_range
    self.assertGreaterEqual(self.json_gen._number(schema), minimum)
AssertionError: 0.0 not greater than or equal to 0.1
----------------------------------------------------------------------
Ran 35 tests in 4.002s
FAILED (failures=1)
Makefile:39: recipe for target 'tests/test_jsongenerator.py' failed
make: *** [tests/test_jsongenerator.py] Error 1
```

**Comment by hannes-ucsc** [comment]
https://travis-ci.org/HumanCellAtlas/data-store/jobs/362441518#L898

**Comment by hannes-ucsc** [comment]
That link is going to become invalid once I restart the job. Here is the output:

```
======================================================================
ERROR: test_generation (__main__.TestHCAGenerator) [assay_bundle.json]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_hcagenerator.py", line 45, in test_generation
    fake_json = self.faker.generate(name)
  File "/home/travis/build/HumanCellAtlas/data-store/dss/util/json_gen/hca_generator.py", line 40, in generate
    generated_json = {name: self._json_gen.generate_json(schema)}
  File "/home/travis/build/HumanCellAtlas/data-store/dss/util/json_gen/generator.py", line 90, in generate_json
    validator.validate(impostor)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 0.0 is less than the minimum of 1e-09

Failed validating 'minimum' in schema['properties']['content']['properties']['imaging']['properties']['exposure_time']:
    {'description': 'Exposure time as a floating point number in units of '
                    'seconds',
     'maximum': 1000,
     'minimum': 1e-09,
     'type': 'number'}

On instance['content']['imaging']['exposure_time']:
    0.0

```
