### ISSUE TITLE
dss-scalability-test fails to deploy

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#1072]
https://travis-ci.org/HumanCellAtlas/data-store/jobs/356101086#L1797

```
cd dss-scalability-test; domovoi deploy --stage dev
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/bin/domovoi", line 104, in <module>
    config = factory.create_config_obj(chalice_stage_name=args.stage, autogen_policy=False)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/chalice/cli/factory.py", line 108, in create_config_obj
    app_obj = self.load_chalice_app()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/chalice/cli/factory.py", line 166, in load_chalice_app
    app = importlib.import_module('app')
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/travis/build/HumanCellAtlas/data-store/daemons/dss-scalability-test/app.py", line 20, in <module>
    from json_generator import generate_sample
  File "/home/travis/build/HumanCellAtlas/data-store/daemons/dss-scalability-test/domovoilib/json_generator/__init__.py", line 5, in <module>
    from tests.json_gen.hca_generator import HCAJsonGenerator
ModuleNotFoundError: No module named 'tests.json_gen'
Makefile:27: recipe for target 'dss-scalability-test' failed
make[1]: *** [dss-scalability-test] Error 1
make[1]: Leaving directory '/home/travis/build/HumanCellAtlas/data-store/daemons'
Makefile:68: recipe for target 'deploy-daemons-parallel' failed
make: *** [deploy-daemons-parallel] Error 2
Script failed with status 2
```

**Comment by hannes-ucsc** [comment]
This holds up deployment of v5 support to dev and integration so I am going to have to remove dss-scalability-test from the daemons Makefile.

**Comment by hannes-ucsc** [comment]
One note about the fix. I think you should just copy the `dss` and `tests` directories into `domovoilib` wholesale in the Makefile instead of copying individual files and making selective imports in a module that's permanently checked into `domovoilib`. If you copy selectively, you are more at risk of breaking again if someone refactors the module dependency or package structure underneath either `dss` or `tests`.

**Comment by kislyuk** [comment]
I disagree about copying `tests` into `domovoilib`. Instead we should move the JSON generator into `dss.util`.
