### ISSUE TITLE
FAIL: test_validate_wrong_key (__main__.TestCheckoutApi)

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1398]
Intermittent unittest failures. with checkout.

https://travis-ci.com/HumanCellAtlas/data-store/jobs/133045587
```
======================================================================
FAIL: test_validate_wrong_key (__main__.TestCheckoutApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_checkout.py", line 269, in test_validate_wrong_key
    self.assertIs(valid, ValidationEnum.WRONG_BUNDLE_KEY, msg=f"cause: {cause}")
AssertionError: <ValidationEnum.WRONG_PERMISSIONS_DST_BUCKET: (<enum.auto object at 0x7f5bdb70de80>,)> is not <ValidationEnum.WRONG_BUNDLE_KEY: (<enum.auto object at 0x7f5bdb70dfd0>,)> : cause: Insufficient permissions on bucket org-humancellatlas-dss-checkout-test
----------------------------------------------------------------------
```

**Comment by kozbo** [comment]
This problem may have been fixed, but we don't have a test case for it. We will close if it doesn't reproduce in the next 7 days.

**Comment by kozbo** [comment]
https://travis-ci.com/HumanCellAtlas/data-store/builds/78461071

======================================================================
FAIL: test_validate_wrong_key (__main__.TestCheckoutApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_checkout.py", line 269, in test_validate_wrong_key
    self.assertIs(valid, ValidationEnum.WRONG_BUNDLE_KEY, msg=f"cause: {cause}")
AssertionError: <ValidationEnum.WRONG_PERMISSIONS_DST_BUCKET: (<enum.auto object at 0x7f813c71ee10>,)> is not <ValidationEnum.WRONG_BUNDLE_KEY: (<enum.auto object at 0x7f813c71ef60>,)> : cause: Insufficient permissions on bucket org-humancellatlas-dss-checkout-test

Problem happened 25 min ago, so still valid

**Comment by mweiden** [comment]
There may be some kind of race condition here.
