### ISSUE TITLE
Integration FAIL: test_bundle_get_presigned (__main__.TestBundleApi)

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1400]
https://travis-ci.com/HumanCellAtlas/data-store/builds/78207561

```
======================================================================

----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_bundle.py", line 127, in test_bundle_get_presigned
    self._test_bundle_get_presigned(Replica.aws)
  File "tests/test_bundle.py", line 146, in _test_bundle_get_presigned
    override_retry_interval=1,
  File "/home/travis/build/HumanCellAtlas/data-store/tests/infra/assert_mixin.py", line 100, in assertResponse
    self.assertEqual(response.status_code, expected_code)
AssertionError: 301 != 200
----------------------------------------------------------------------
```

**Comment by Bento007** [comment]
@ttung any ideas?

**Comment by ttung** [comment]
I'd check the logs to see if the copy does eventually succeed.  If so, then we just need to extend the timeout.  If it doesn't succeed, we need to figure out why not.

**Comment by mweiden** [comment]
We haven't seen this bug in the last two weeks of test runs. Closing this now. We will reopen it if it recurs.
