### ISSUE TITLE
Integration  ERROR: test_storage_verification_blobs (__main__.TestIntegration)

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1401]
```
======================================================================
ERROR: test_storage_verification_blobs (__main__.TestIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_visitation.py", line 294, in test_storage_verification_blobs
    self._test('storage', '--replica=aws', '--replica=gcp', '--prefix=423', 'verify', '--folder=blobs')
  File "tests/test_visitation.py", line 306, in _test
    output = self._get_execution_output(arn)
  File "/home/travis/build/HumanCellAtlas/data-store/tests/__init__.py", line 83, in call
    return func(*args, **kwargs)
  File "tests/test_visitation.py", line 315, in _get_execution_output
    require(status in ('SUCCEEDED', 'RUNNING'), f'Unexpected execution status: {status}')
  File "/home/travis/build/HumanCellAtlas/data-store/dss/util/__init__.py", line 91, in require
    reject(not condition, *args, exception=exception)
  File "/home/travis/build/HumanCellAtlas/data-store/dss/util/__init__.py", line 106, in reject
    raise exception(*args)
dss.util.RequirementError: Unexpected execution status: FAILED
----------------------------------------------------------------------
```

**Comment by hannes-ucsc** [comment]
Could you check if this is the same cause as in #1391? 

If so please file a support request against AWS.
