### ISSUE TITLE
Integration FAIL: test_status_fail (__main__.TestCheckoutApi)

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1402]
```
======================================================================
FAIL: test_status_fail (__main__.TestCheckoutApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_checkout.py", line 201, in test_status_fail
    check_status()
  File "/home/travis/build/HumanCellAtlas/data-store/tests/__init__.py", line 83, in call
    return func(*args, **kwargs)
  File "tests/test_checkout.py", line 199, in check_status
    self.assertEqual(status, "FAILED")
AssertionError: 'RUNNING' != 'FAILED'
- RUNNING
+ FAILED
----------------------------------------------------------------------
```

**Comment by mweiden** [comment]
This may be related to https://app.zenhub.com/workspace/o/humancellatlas/data-store/issues/1391

**Comment by Bento007** [comment]
#1407 fixed this.

**Comment by ttung** [comment]
Ummm, I don't think #1407 fixed this.  It just made it easier to track things down should it recur.  But I'll take the close. :)
