### ISSUE TITLE
FAIL: test_file_put_large (__main__.TestFileApi)

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1408]
https://travis-ci.com/HumanCellAtlas/data-store/builds/78447026
```
======================================================================
FAIL: test_file_put_large (__main__.TestFileApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_file.py", line 104, in test_file_put_large
    self._test_file_put_large(Replica.aws, self.s3_test_bucket, upload_callable_creator(S3Uploader))
  File "tests/test_file.py", line 119, in _test_file_put_large
    expect_async=expect_async)
  File "/home/travis/build/HumanCellAtlas/data-store/tests/infra/upload_mixin.py", line 70, in upload_file_wait
    self.fail("Could not find the output file")
AssertionError: Could not find the output file
----------------------------------------------------------------------
```

**Comment by Bento007** [comment]
Issue has not been seen in over 14 days.
