### ISSUE TITLE
AWS to GCP replication caused Smoketest to fail

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1447]
## Software version (git hash, date, branch)
https://github.com/HumanCellAtlas/data-store/commit/02fe5d891722c52bbf6f39f28b04a0eb70070e27
## Expected behavior
This should not fail.

## Actual behavior
https://travis-ci.com/HumanCellAtlas/data-store/builds/79918152

- Replication failed from aws to gcp
```
======================================================================
ERROR: test_smoketest (__main__.Smoketest) [aws: Wait for the bundle to appear in the Replica.gcp replicas]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_smoketest.py", line 171, in smoketest
    parser.exit(RED(f"Failed to replicate bundle from {starting_replica.name} to {replica.name}"))
  File "/opt/python/3.6.3/lib/python3.6/argparse.py", line 2376, in exit
    _sys.exit(status)
SystemExit: Failed to replicate bundle from aws to gcp
```
- notifications failed for aws and gcp
```
======================================================================
ERROR: test_smoketest (__main__.Smoketest) [aws: Check the notifications. gcp, 14d62183-f5f6-4a82-a0e5-7c42df59a2a8, notifications/bdcecf2b-db7d-4159-b8cc-712bcd04f44d]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_smoketest.py", line 207, in smoketest
    obj = s3.get_object(Bucket=self.notification_bucket, Key=notification_key)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
======================================================================
ERROR: test_smoketest (__main__.Smoketest) [aws: Check the notifications. aws, 8ffc1322-6500-48c4-aff7-5b75a934da42, notifications/c5b5142f-fbdb-40b4-a1e9-fa583f1a7722]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_smoketest.py", line 207, in smoketest
    obj = s3.get_object(Bucket=self.notification_bucket, Key=notification_key)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
```

- search failed for aws and gcp
```
======================================================================
FAIL: test_smoketest (__main__.Smoketest) [aws: Hit search route directly against each replica Replica.gcp]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_smoketest.py", line 182, in smoketest
    self.assertEqual(len(res['results']), 1)
AssertionError: 0 != 1
======================================================================
FAIL: test_smoketest (__main__.Smoketest) [aws: Hit search route directly against each replica Replica.aws]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_smoketest.py", line 182, in smoketest
    self.assertEqual(len(res['results']), 1)
AssertionError: 0 != 1
```
## Steps to reproduce the behavior
Have not yet reproduced

**Comment by Bento007** [comment]
Issues has not occurred in a month.
