### ISSUE TITLE
Sync unit test needs to be more resilient to cleanup errors

### ISSUE THREAD

**Issue by kislyuk** [HumanCellAtlas/data-store#1589]
```
======================================================================
ERROR: test_sync_blob (__main__.TestSyncUtils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_sync.py", line 56, in test_sync_blob
    self.cleanup_sync_test_objects()
  File "tests/test_sync.py", line 53, in cleanup_sync_test_objects
    key.delete()
  File "/home/hca_cicd/venv/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 408, in delete
    return self.bucket.delete_blob(self.name, client=client)
  File "/home/hca_cicd/venv/lib/python3.6/site-packages/google/cloud/storage/bucket.py", line 633, in delete_blob
    _target_object=None)
  File "/home/hca_cicd/venv/lib/python3.6/site-packages/google/cloud/_http.py", line 293, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://www.googleapis.com/storage/v1/b/org-humancellatlas-dss-test/o/hca-dss-sync-test%2Fcompose-gs-blobs%2F5593f923-ad69-4052-a6ef-6e993dc678a1: No such object: org-humancellatlas-dss-test/hca-dss-sync-test/compose-gs-blobs/5593f923-ad69-4052-a6ef-6e993dc678a1

----------------------------------------------------------------------
Ran 6 tests in 4.574s

FAILED (errors=1)
```

**Comment by kozbo** [comment]
We need to meet with Trent and Brian to review this.
