### ISSUE TITLE
Reasonable default for GOOGLE_APPLICATION_CREDENTIALS variable missing from environment file(s)

### ISSUE THREAD

**Issue by brainstorm** [HumanCellAtlas/data-store#1712]
Related with issue #1593.

## Software version (git hash, date, branch)
81547e1
2018-11-14
master

## Expected behavior
Have `GOOGLE_APPLICATION_CREDENTIALS="$HOME/data-store/gcp-credentials.json"` defined by default in `environment.local.example` (perhaps also in `environment`?) file so that when copying it to `environment.local` the google cloud cli finds it, i.e:

```
(hca-venv) ubuntu@ip-172-31-21-87:~/data-store$ cat environment | grep GOOGLE
(...)
GOOGLE_APPLICATION_CREDENTIALS_SECRETS_NAME="gcp-credentials.json"
GOOGLE_APPLICATION_SECRETS_SECRETS_NAME="application_secrets.json"

(hca-venv) ubuntu@ip-172-31-21-87:~/data-store$ cat environment.local | grep GOOGLE
GOOGLE_APPLICATION_CREDENTIALS="$HOME/data-store/gcp-credentials.json"
GOOGLE_APPLICATION_CREDENTIALS_SECRETS_NAME="gcp-credentials.json"
GOOGLE_APPLICATION_SECRETS_SECRETS_NAME="application_secrets.json"
```

## Actual behavior

```
make deploy-infra
(...)
rm -rf buckets/.terraform/*.tfstate
./build_deploy_config.py buckets
Traceback (most recent call last):
  File "./build_deploy_config.py", line 9, in <module>
    GCP_PROJECT_ID = Client().project
  File "/home/ubuntu/hca-venv/lib/python3.7/site-packages/google/cloud/storage/client.py", line 71, in __init__
    _http=_http)
  File "/home/ubuntu/hca-venv/lib/python3.7/site-packages/google/cloud/client.py", line 215, in __init__
    _ClientProjectMixin.__init__(self, project=project)
  File "/home/ubuntu/hca-venv/lib/python3.7/site-packages/google/cloud/client.py", line 169, in __init__
    project = self._determine_default(project)
  File "/home/ubuntu/hca-venv/lib/python3.7/site-packages/google/cloud/client.py", line 182, in _determine_default
    return _determine_default_project(project)
  File "/home/ubuntu/hca-venv/lib/python3.7/site-packages/google/cloud/_helpers.py", line 179, in _determine_default_project
    _, project = google.auth.default()
  File "/home/ubuntu/hca-venv/lib/python3.7/site-packages/google/auth/_default.py", line 306, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://developers.google.com/
accounts/docs/application-default-credentials.
make[2]: *** [Makefile:44: init] Error 1
make[2]: Leaving directory '/home/ubuntu/data-store/infra'
make[1]: *** [Makefile:17: apply-all] Error 1
make[1]: Leaving directory '/home/ubuntu/data-store/infra'
make: *** [Makefile:80: deploy-infra] Error 2
```

## Steps to reproduce the behavior

Follow the README.md fixing all bugs along, all the way to the deployment command:

`make deploy-infra`

**Comment by DailyDreaming** [comment]
This issue is old and the subsequent follow-up including this in `environment.local.example` was closed so I'm closing this too.

My opinion is also that we also shouldn't include this in the main environment file because it will overwrite the usual credentials set by anyone who works with Google regularly (and it's better to set this in the bashrc).
