### ISSUE TITLE
make deploy-infra: not authorized to perform: apigateway:POST

### ISSUE THREAD

**Issue by brainstorm** [HumanCellAtlas/data-store#1721]
## Software version (git hash, date, branch)

81547e1
2018-11-14
master

## Expected behavior

I would have expected that the certificate requesting process has enough permissions to carry on the AWS side, but the AWS (minimal) AWS policies required for that are not documented nor implemented.

## Actual behavior
```
null_resource.dss_domain: Creating...
null_resource.dss_domain: Provisioning with 'local-exec'...
null_resource.dss_domain (local-exec): Executing: ["/bin/sh" "-c" "./create_regional_domain_name.py --domain-name SUBDOMAIN.umccr.org --certificate-arn arn:aws:acm:ap-southeast-2:ACCOUNT_ID:certificate/HASH --zone-id ZONE_ID"]
null_resource.dss_domain (local-exec): Traceback (most recent call last):
null_resource.dss_domain (local-exec):   File "./create_regional_domain_name.py", line 21, in <module>
null_resource.dss_domain (local-exec):     endpointConfiguration={'types': ["REGIONAL"]}
null_resource.dss_domain (local-exec):   File "/home/ubuntu/hca-venv/lib/python3.7/site-packages/botocore/client.py", line 314, in _api_call
null_resource.dss_domain (local-exec):     return self._make_api_call(operation_name, kwargs)
null_resource.dss_domain (local-exec):   File "/home/ubuntu/hca-venv/lib/python3.7/site-packages/botocore/client.py", line 612, in _make_api_call
null_resource.dss_domain (local-exec):     raise error_class(parsed_response, operation_name)
null_resource.dss_domain (local-exec): botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the CreateDomainName operation: User: arn:aws:sts::ACCOUNT_ID:assumed-role/UNDER_DOCUMENTED_HCA_ROLE/i-0fff715198f95c782 is not authorized to perform: apigateway:POST on resource: arn:aws:apigateway:ap-southeast-2::/domainnames
```

## Steps to reproduce the behavior

`make deploy-infra` during the certificate generation and validation step.

**Comment by melainalegaspi** [comment]
Creating a domain is now done manually, taken out of Terraform
