### ISSUE TITLE
make deploy: Unable to import module 'app': No module named 'inflection'

### ISSUE THREAD

**Issue by brainstorm** [HumanCellAtlas/data-store#1740]
## Software version (git hash, date, branch)
15dcdc4 (HEAD -> master, origin/master, origin/HEAD) HEAD@{0}: pull: Fast-forward

## Expected behavior
`make deploy` should deploy the DSS application.

## Actual behavior
```
Created new state machine arn:aws:states:ap-southeast-2:ACCOUNT_ID:stateMachine:dss-sync-sfn-dev
State machine: arn:aws:states:ap-southeast-2:ACCOUNT_ID:stateMachine:dss-sync-sfn-dev
upload: ../tests/daemons/LONG_HASH.TIMESTAMP to s3://org-umccr-hca-dss-dev/bundles/LONG_HASH.TIMESTAMP
eSTART RequestId: LONG_HASH Version: $LATEST
Unable to import module 'app': No module named 'inflection'

END RequestId: LONG_HASH
REPORT RequestId: LONG_HASH  Duration: 0.62 ms       Billed Duration: 100 ms         Memory Size: 1536 MB    Max Memory Used: 41 MB
make[1]: *** [Makefile:35: dss-sync-sfn] Error 1
make[1]: Leaving directory '/home/ubuntu/data-store/daemons'
make: *** [Makefile:71: deploy-daemons-serial] Error 2
```

## Steps to reproduce the behavior
`make deploy`

**Comment by brainstorm** [comment]
I could trace it back to this earlier in the `make deploy` log:

```
chalice deploy --no-autogen-policy --stage dev --api-gateway-stage dev
Creating deployment package.

Could not install dependencies:
wrapt==1.10.11
google-apitools==0.5.24
cffi==1.11.5
pycparser==2.19
markupsafe==1.1.0
httplib2==0.11.3
inflection==0.3.1
crcmod==1.7
googleapis-common-protos==1.5.5
pyyaml==3.13
future==0.17.1
You will have to build these yourself and vendor them in
the chalice vendor folder.

Your deployment will continue but may not work correctly
if missing dependencies are not present. For more information:
http://chalice.readthedocs.io/en/latest/topics/packaging.html
```

Investigating what went wrong there...

**Comment by brainstorm** [comment]
Strange since creating a fresh venv and installing those requirements there seems to work flawlessly:

```
(hca-venv-dev) ubuntu@ip-172-31-21-87:~/hca-venv-dev/test$ pip install -r requirements.txt
Collecting wrapt==1.10.11 (from -r requirements.txt (line 1))
Collecting google-apitools==0.5.24 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/a9/74/14b0618bfd2c02fbddadbfa1d74e0e141e25fbea9e9197e41eddadbb1299/google-apitools-0.5.24.tar.gz
Collecting cffi==1.11.5 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/51/7b/d1014289d0578c3522b2798b9cb87c65e5b36798bd3ae68a75fa1fe09e78/cffi-1.11.5-cp37-cp37m-manylinux1_x86_64.whl
Collecting pycparser==2.19 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz
Collecting markupsafe==1.1.0 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/e4/c4/adcc2d6f2ac2146cc04e076f14f1006c1de8e1e747fa067668b6573000b8/MarkupSafe-1.1.0-cp37-cp37m-manylinux1_x86_64.whl
Collecting httplib2==0.11.3 (from -r requirements.txt (line 6))
Collecting inflection==0.3.1 (from -r requirements.txt (line 7))
Collecting crcmod==1.7 (from -r requirements.txt (line 8))
Collecting googleapis-common-protos==1.5.5 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/ae/94/a256572abf5d10347301c638d5df552fab1515497270726e6b56698d2e99/googleapis-common-protos-1.5.5.tar.gz
Collecting pyyaml==3.13 (from -r requirements.txt (line 10))
Collecting future==0.17.1 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz
Collecting fasteners>=0.14 (from google-apitools==0.5.24->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/14/3a/096c7ad18e102d4f219f5dd15951f9728ca5092a3385d2e8f79a7c1e1017/fasteners-0.14.1-py2.py3-none-any.whl
Collecting oauth2client>=1.4.12 (from google-apitools==0.5.24->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/95/a9/4f25a14d23f0786b64875b91784607c2277eff25d48f915e39ff0cff505a/oauth2client-4.1.3-py2.py3-none-any.whl
Collecting six>=1.9.0 (from google-apitools==0.5.24->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting protobuf>=3.0.0 (from googleapis-common-protos==1.5.5->-r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/3a/30/289ead101f94998d88e8961a3548aea29417ae0057be23972483cddebf4f/protobuf-3.6.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting monotonic>=0.1 (from fasteners>=0.14->google-apitools==0.5.24->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/ac/aa/063eca6a416f397bd99552c534c6d11d57f58f2e94c14780f3bbf818c4cf/monotonic-1.5-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.0.5 (from oauth2client>=1.4.12->google-apitools==0.5.24->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/19/02/fa63f7ba30a0d7b925ca29d034510fc1ffde53264b71b4155022ddf3ab5d/pyasn1_modules-0.2.2-py2.py3-none-any.whl
Collecting pyasn1>=0.1.7 (from oauth2client>=1.4.12->google-apitools==0.5.24->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/d1/a1/7790cc85db38daa874f6a2e6308131b9953feb1367f2ae2d1123bb93a9f5/pyasn1-0.4.4-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from oauth2client>=1.4.12->google-apitools==0.5.24->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /home/ubuntu/hca-venv-dev/lib/python3.7/site-packages (from protobuf>=3.0.0->googleapis-common-protos==1.5.5->-r requirements.txt (line 9)) (39.0.1)
Installing collected packages: wrapt, httplib2, six, monotonic, fasteners, pyasn1, pyasn1-modules, rsa, oauth2client, google-apitools, pycparser, cffi, markupsafe, inflection, crcmod, protobuf, googleapis-common-protos, pyyaml, future
  Running setup.py install for google-apitools ... done
  Running setup.py install for pycparser ... done
  Running setup.py install for googleapis-common-protos ... done
  Running setup.py install for future ... done
Successfully installed cffi-1.11.5 crcmod-1.7 fasteners-0.14.1 future-0.17.1 google-apitools-0.5.24 googleapis-common-protos-1.5.5 httplib2-0.11.3 inflection-0.3.1 markupsafe-1.1.0 monotonic-1.5 oauth2client-4.1.3 protobuf-3.6.1 pyasn1-0.4.4 pyasn1-modules-0.2.2 pycparser-2.19 pyyaml-3.13 rsa-4.0 six-1.11.0 wrapt-1.10.11
```

Looking at chalice packaging URL next...

**Comment by brainstorm** [comment]
Will downgrade to python3.6 as mentioned in https://github.com/HumanCellAtlas/data-store/issues/1684#issuecomment-440538492 since AWS lambdas run on py3.6. But doing so leads to some more interesting bugs (this time on AWS's Chalice, not `data-store`:

```
chalice deploy --no-autogen-policy --stage dev --api-gateway-stage dev
/home/ubuntu/miniconda3/lib/python3.7/site-packages/chalice/deploy/validate.py:24: UserWarning: You are currently running python3.7, but the closest supported version on AWS Lambda is python3.6
Please use python3.6, otherwise you may run into deployment issues.
  validate_python_version(config)
Creating deployment package.
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/chalice/cli/__init__.py", line 447, in main
    return cli(obj={})
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/chalice/cli/__init__.py", line 183, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/chalice/deploy/deployer.py", line 330, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/chalice/deploy/deployer.py", line 340, in _deploy
    self._build_stage.execute(config, resources)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/chalice/deploy/deployer.py", line 823, in execute
    step.handle(config, resource)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/chalice/deploy/deployer.py", line 721, in handle
    handler(config, resource)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/chalice/deploy/deployer.py", line 748, in handle_deploymentpackage
    config.project_dir, config.lambda_python_version
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/chalice/deploy/packager.py", line 84, in create_deployment_package
    requirements_filepath, site_packages_dir)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/chalice/deploy/packager.py", line 478, in build_site_packages
    tempdir, requirements_filepath)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/chalice/deploy/packager.py", line 357, in _download_dependencies
    requirements_filename, directory)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/chalice/deploy/packager.py", line 319, in _download_all_dependencies
    self._pip.download_all_dependencies(requirements_filename, directory)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/chalice/deploy/packager.py", line 716, in download_all_dependencies
    raise PackageDownloadError(error)
chalice.deploy.packager.PackageDownloadError: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'main' from 'pip' (/home/ubuntu/miniconda3/lib/python3.7/site-packages/pip/__init__.py)


make[1]: *** [Makefile:10: deploy] Error 2
make[1]: Leaving directory '/home/ubuntu/data-store/chalice'
make: *** [Makefile:66: deploy-chalice] Error 2


(hca-venv-py36) ubuntu@ip-172-31-21-87:~/data-store$ python --version
Python 3.6.7
(hca-venv-py36) ubuntu@ip-172-31-21-87:~/data-store$ pip --version
pip 18.1 from /home/ubuntu/data-store/hca-venv-py36/lib/python3.6/site-packages/pip (python 3.6)
```

**Comment by brainstorm** [comment]
So I created a py36 environment, the py37 warning went away but still there's something off with the `inflection` module:

```
cd dss-sync-sfn && domovoi deploy --stage dev
Regen deployment package.
Updating policy for IAM role: dss-sync-sfn-dev
Updating lambda function: dss-sync-sfn-dev
Granting apigateway access to invoke Lambda function arn:aws:lambda:ap-southeast-2:ACCOUNT_ID:function:dss-sync-sfn-dev
Found existing permission grant statement domovoi-3406ea52, skipping
Granting events access to invoke Lambda function arn:aws:lambda:ap-southeast-2:ACCOUNT_ID:function:dss-sync-sfn-dev
Found existing permission grant statement domovoi-71726b79, skipping
Granting sns access to invoke Lambda function arn:aws:lambda:ap-southeast-2:ACCOUNT_ID:function:dss-sync-sfn-dev
Found existing permission grant statement domovoi-341ca53c, skipping
Granting sqs access to invoke Lambda function arn:aws:lambda:ap-southeast-2:ACCOUNT_ID:function:dss-sync-sfn-dev
Found existing permission grant statement domovoi-6bab6ebc, skipping
Granting s3 access to invoke Lambda function arn:aws:lambda:ap-southeast-2:ACCOUNT_ID:function:dss-sync-sfn-dev
Found existing permission grant statement domovoi-34b69d0c, skipping
Granting logs access to invoke Lambda function arn:aws:lambda:ap-southeast-2:ACCOUNT_ID:function:dss-sync-sfn-dev
Found existing permission grant statement domovoi-a892fc00, skipping
Subscribing <function launch_from_forwarded_event at 0x7f41a9fa17b8> to SQS queue dss-sync-dev
Subscribing <function launch_from_s3_event at 0x7f41a9fa1730> to events in S3 bucket org-umccr-hca-dss-dev
Subscribed arn:aws:sqs:ap-southeast-2:ACCOUNT_ID:domovoi-s3-bucket-events-org-umccr-hca-dss-dev-dss-sync-sfn-dev to sns.Subscription(arn='arn:aws:sns:ap-southeast-2:ACCOUNT_ID:domovoi-s3-bucket-events-org-umccr-hca-dss-dev:HASH')
Created event source mapping HASH
Registering step function state machine for DispatchSync
Registering step function state machine for Worker0
Registering step function state machine for Worker1
Registering step function state machine for Worker2
Registering step function state machine for Worker3
Registering step function state machine for Worker4
Registering step function state machine for Worker5
Registering step function state machine for Worker6
Registering step function state machine for Worker7
Registering step function state machine for CheckDeps
Registering step function state machine for OneshotCopy
Registering step function state machine for ComposeParts
Created new state machine arn:aws:states:ap-southeast-2:ACCOUNT_ID:stateMachine:dss-sync-sfn-dev
State machine: arn:aws:states:ap-southeast-2:ACCOUNT_ID:stateMachine:dss-sync-sfn-dev
2018-11-21 06:23:49         94 HASH
eSTART RequestId: HASH Version: $LATEST
Unable to import module 'app': No module named 'inflection'

END RequestId: HASH
REPORT RequestId: HASH  Duration: 0.54 ms       Billed Duration: 100 ms         Memory Size: 1536 MB    Max Memory Used: 41 MB
make[1]: *** [Makefile:35: dss-sync-sfn] Error 1
make[1]: Leaving directory '/home/ubuntu/data-store/daemons'
make: *** [Makefile:71: deploy-daemons-serial] Error 2
```

**Comment by Bento007** [comment]
stale
