### ISSUE TITLE
`post_search.iterate` failure

### ISSUE THREAD

**Issue by mckinsel** [HumanCellAtlas/data-store#1771]
## Software version
dcp-cli 4.4.10
https://dss.data.humancellatlas.org/v1
## Expected behavior
This should work:
```python
import hca.dss
client = hca.dss.DSSClient()
for _ in client.post_search.iterate(es_query={}, replica="aws"):
    pass
```
## Actual behavior
This happens:
```python
import hca.dss
client = hca.dss.DSSClient()
for _ in client.post_search.iterate(es_query={}, replica="aws"):
    pass
SwaggerAPIException: unhandled_exception: sequence item 0: expected str instance, NoneType found (HTTP 500). Details:
Traceback (most recent call last):
  File "/var/task/chalicelib/dss/error.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/var/task/chalicelib/dss/api/search.py", line 80, in post
    next_url = _build_next_url(page, per_page, replica_enum, output_format)
  File "/var/task/chalicelib/dss/api/search.py", line 150, in _build_next_url
    search_after = ','.join(page['hits']['hits'][-1]['sort'])
TypeError: sequence item 0: expected str instance, NoneType found
```
## Steps to reproduce the behavior
Run that code.

**Comment by amarjandu** [comment]
## Issues Observed 
Issues found within PROD, paged results fail after 34300 results are returned, total hits from the es_query should be 38827.
page breaks after `search_after='2018-01-02T230803.681393Z,3c23ea58-b0f7-4470-8491-f068125dfb72'`
Changes to `per_page` size does not change the point at which the failure occurs.
Attempting to send a new request with the `search_after` parameter set to the place where the break occurs instantly fails.

## Awaiting

Currently waiting staging to be promoted to prod, issue does not exist within staging. This should happen within the next week.

**Comment by mckinsel** [comment]
Hey thanks @amarjandu, just a couple quick thoughts:

1. I think I observed it happen after a variable number of bundles. I'm not sure how deterministic the return order is from `/search`.
2. Is it possible it's some sort of rogue bundle that breaks the DSS somehow? If that's the case, waiting for staging promotion won't help.

**Comment by amarjandu** [comment]
@mckinsel You are absolutely right, i went back and adjusted some of the values for the per_page, and can see that it's failing at different iterations and bundle files, it seems the larger the per_page, the sooner it fails. ill do some more digging into this. 

I've updated my previous WIP notes.

**Comment by mckinsel** [comment]
There was just a deployment to prod, and the issue still exists.

**Comment by xbrianh** [comment]
@mckinsel @amarjandu This appears to be an interaction with Tombstones. Iterating over `query = {'query':{'bool':{'must_not':{'term':{'admin_deleted':True}}}}}` succeeds, while `query = {'query':{'bool':{'must':{'term':{'admin_deleted':True}}}}}` fails immediately.
