### ISSUE TITLE
Elasticsearch 429s are unhandled

### ISSUE THREAD

**Issue by mckinsel** [HumanCellAtlas/data-store#1801]
When Elasticsearch gets busy, this happens when you POST to `search`:

```
Traceback (most recent call last):
  File "/var/task/chalicelib/dss/api/search.py", line 45, in post
    page = _es_search_page(es_query, replica_enum, per_page, search_after, output_format)
  File "/var/task/chalicelib/dss/api/search.py", line 107, in _es_search_page
    sort=sort
  File "/var/task/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/var/task/elasticsearch/client/__init__.py", line 632, in search
    doc_type, '_search'), params=params, body=body)
  File "/var/task/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/var/task/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/var/task/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.TransportError: TransportError(429, 'search_phase_execution_exception', 'rejected execution of org.elasticsearch.transport.TransportService$7@2c9f6371 on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@779bc898[Running, pool size = 4, active threads = 4, queued tasks = 1000, completed tasks = 27526394]]')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/chalicelib/dss/error.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/var/task/chalicelib/dss/api/search.py", line 66, in post
    "Elasticsearch Internal Server Error")
dss.error.DSSException```

**Comment by Bento007** [comment]
was this test run on production, and what type of load where you running on the system?

**Comment by mckinsel** [comment]
It was in production. I saw it when trying to figure out this behavior:

```
http POST 'https://dss.data.humancellatlas.org/v1/search?per_page=100&replica=aws&search_after=2018-03-29t141803.318968z%2C5ec6d9f9-a68b-4fc7-9044-a5653b6e50eb&output_format=summary' es_query:='{}'
```

**Comment by Bento007** [comment]
Then it looks like we will need to do some investigating and possibly increase the size of the elastic search instance.

**Comment by xbrianh** [comment]
Prod ES domain scaled up.
