### ISSUE TITLE
Update urllib3.

### ISSUE THREAD

**Issue by DailyDreaming** [HumanCellAtlas/data-store#2109]
Right now snyk is failing because urllib3 is not the latest version, however, upgrading to the latest version seems to enforce a machine specific SSL check that fails multiple tests:
```
======================================================================
ERROR: test_copy_part_gs_to_s3 (__main__.TestSyncUtils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 345, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
```
https://travis-ci.com/HumanCellAtlas/data-store/jobs/198397296

Low priority in my eyes, but posting this here until resolved.

**Comment by kozbo** [comment]
Can this be closed now that #2122 has been merged?

**Comment by xbrianh** [comment]
That PR was reverted, @kozbo.

@DailyDreaming Do you know the status of this ticket?

**Comment by DailyDreaming** [comment]
@xbrianh Sorry I didn't see this.  I didn't follow up with it but it needs cert validation on the gitlab runners.  It passed locally for me since the certs were up to date.
