### ISSUE TITLE
Ability to refresh token or pass authentication headers  in DSS python client methods

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/data-store#2216]
User story:
• As a DSS python client user
• I want to know to pass JWT token in Authorisation headers
• so that I can have one instance of DSS client in my code and manage the tokens on my own

We're encountering the following error after sometime in our exporters: 
```
Error in hca_client.put_file method call with params:{"uuid": "d45d8bad-12f2-4a19-a17d-40f24becd960", "version": "2019-06-24T040518.081000Z", "creator_uid": 8008, "source_url": "s3://org-humancellatlas-upload-dev/8dd83c15-590c-4c76-8abc-67b7ae3a1740/biomaterial_d45d8bad-12f2-4a19-a17d-40f24becd960.json"} due to Unauthorized: Authorization token is invalid (HTTP 401). Details:
Traceback (most recent call last):
  File "/var/task/chalicelib/dss/util/security.py", line 69, in verify_jwt
    algorithms=allowed_algorithms,
  File "/opt/python/lib/python3.6/site-packages/jwt/api_jwt.py", line 104, in decode
    self._validate_claims(payload, merged_options, **kwargs)
  File "/opt/python/lib/python3.6/site-packages/jwt/api_jwt.py", line 134, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "/opt/python/lib/python3.6/site-packages/jwt/api_jwt.py", line 175, in _validate_exp
    raise ExpiredSignatureError('Signature has expired')
jwt.exceptions.ExpiredSignatureError: Signature has expired

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/python/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/python/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 73, in wrapper
    response = function(request)
  File "/opt/python/lib/python3.6/site-packages/connexion/decorators/security.py", line 113, in wrapper
    token_info = token_info_func(token)
  File "/var/task/chalicelib/dss/util/security.py", line 74, in verify_jwt
    raise DSSException(401, 'Unauthorized', 'Authorization token is invalid') from ex
dss.error.DSSException
```

Our exporter instance is a long running python listener and only instantiates one instance of DSS client. It seems that the token in the DSS client is not being automatically refreshed and to workaround the token expiration, we would always instantiate a new instance of DSS every time we try to make a bundle. It would be nice remove this re-instantiation by letting us pass the token headers every time we call a method from DSS client.

**Comment by aaclan-ebi** [comment]
Hi @DailyDreaming , just want to ask, do you have an approx date when this functionality can be supported? 

We have an imaging dataset failing in staging due to expired token. There were 2k files that needs to be uploaded and it's taking more than an hour before we get to create the bundle. As a workaround, we could always instantiate the HCA DSS client in our code every time we do put_file, put_bundle methods to avoid the token from expiring.

**Comment by aaclan-ebi** [comment]
Question: Is the DSS Client instantiation slow/resource heavy? do you see any issues if we try to instantiate it every time we do PUT/GET method calls?

**Comment by aaclan-ebi** [comment]
Hi @DailyDreaming , has this been implemented? Do we need to change something on our end?

Thanks!
