### ISSUE TITLE
Hca Dev Update Indexing

### ISSUE THREAD

**Issue by jeffrey856** [HumanCellAtlas/data-store#2261]
While running on dev I am getting this error: 
```hca dss post-bundles-checkout --replica aws --uuid fe4553cf-ab1b-47b9-ad34-5d5055a2f465 --version 2019-05-07T163612.751435Z```
```Traceback (most recent call last):
  File "/home/jeff/.local/bin/hca", line 10, in <module>
    sys.exit(main())
  File "/home/jeff/.local/lib/python3.6/site-packages/hca/cli.py", line 138, in main
    result = parsed_args.entry_point(parsed_args)
  File "/home/jeff/.local/lib/python3.6/site-packages/hca/util/__init__.py", line 200, in _cli_call
    return self._consume_response(self._request(vars(cli_args)))
  File "/home/jeff/.local/lib/python3.6/site-packages/hca/util/__init__.py", line 185, in _request
    raise SwaggerAPIException(response=res)
hca.util.exceptions.SwaggerAPIException: not_found: Cannot find bundle! (HTTP 404). Details:
Traceback (most recent call last):
  File "/var/task/chalicelib/dss/api/bundles/checkout.py", line 24, in post
    email_address=json_request_body.get('email', None),
  File "/var/task/chalicelib/dss/storage/checkout/bundle.py", line 46, in start_bundle_checkout
    raise BundleNotFoundError()
dss.storage.checkout.error.BundleNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/chalicelib/dss/error.py", line 59, in wrapper
    return func(*args, **kwargs)
  File "/var/task/chalicelib/dss/api/bundles/checkout.py", line 27, in post
    raise DSSException(404, "not_found", "Cannot find bundle!")
dss.error.DSSException
````
Please update indexing.

**Comment by amarjandu** [comment]
Jeff, what {stage} was this in?

**Comment by kozbo** [comment]
When closing an issue please include the reason.
