### ISSUE TITLE
Prod serving bad bundles.

### ISSUE THREAD

**Issue by DailyDreaming** [HumanCellAtlas/data-store#2330]
Prod most likely probably needs to be reindexed due to recent tombstoning.  I'm getting a massive number of bad bundles.

To reproduce:
```
from hca import HCAConfig
from hca.dss import DSSClient


hca_config = HCAConfig()
hca_config["DSSClient"].swagger_url = f"https://dss.data.humancellatlas.org/v1/swagger.json"
dss = DSSClient(config=hca_config)

# JSON query and returns matching bundle identifiers.
for results in dss.post_search.iterate(replica="aws", es_query={}):
    uuid, version = results["bundle_fqid"].split(".", 1)
    r = dss.get_bundle(replica="aws", uuid=uuid, version=version)["bundle"]["files"]
```

```
Traceback (most recent call last):
  File "/home/quokka/delete/data-store/scrap2.py", line 12, in <module>
    r = dss.get_bundle(replica="aws", uuid=uuid, version=version)["bundle"]["files"]
  File "/home/quokka/git/delete/data-store/v3nv/lib/python3.6/site-packages/hca/util/__init__.py", line 197, in __call__
    return self._consume_response(self._request(kwargs))
  File "/home/quokka/git/delete/data-store/v3nv/lib/python3.6/site-packages/hca/util/__init__.py", line 185, in _request
    raise SwaggerAPIException(response=res)
hca.util.exceptions.SwaggerAPIException: not_found: Cannot find bundle! (HTTP 404). Details:
Traceback (most recent call last):
  File "/var/task/chalicelib/dss/error.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/var/task/chalicelib/dss/api/bundles/__init__.py", line 54, in get
    raise DSSException(404, "not_found", "Cannot find bundle!")
dss.error.DSSException
```

**Comment by DailyDreaming** [comment]
I was under the false impression that we did not serve tombstoned bundles.  To navigate around this, a filter can be used to return only non-tombstoned bundles: `{"query": {"bool": {"must_not": {"term": {"admin_deleted": true}}}}}`

Hopefully this behavior will change when we move from `elasticsearch` to the `query-service`. Closing this.
