### ISSUE TITLE
Intermittent test failure: tests/test_file.py TestFileApi.test_file_get_checkout

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#2340]
```
======================================================================
FAIL: test_file_get_checkout (__main__.TestFileApi) [Replica.aws: Initiates checkout and returns 302 immediately for GET on stale checkout file.]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_file.py", line 721, in _test_file_get_checkout
    test_creation_date_updated(file_key, old_creation_date)
  File "/home/travis/build/HumanCellAtlas/data-store/tests/__init__.py", line 73, in call
    return func(*args, **kwargs)
  File "tests/test_file.py", line 709, in test_creation_date_updated
    self.assertTrue(prev_creation_date < handle.get_creation_date(replica.checkout_bucket, key))
AssertionError: False is not true
----------------------------------------------------------------------
```

**Comment by xbrianh** [comment]
this error reoccurred.

**Comment by DailyDreaming** [comment]
@xbrianh Could you post a link?

**Comment by xbrianh** [comment]
@DailyDreaming It occurred on a Travis build which I retried, so unfortunately no.
