### ISSUE TITLE
How to run local indexing test with local elasticsearch instance

### ISSUE THREAD

**Issue by chmreid** [HumanCellAtlas/data-store#2459]
## Software version (git hash, date, branch)

Using the `master` branch

## Expected behavior

When I run the indexer tests with

```
python tests/test_indexer.py
```

I expect the tests to work, if I have elasticsearch installed locally.

## Actual behavior

Tests fail with the following errors:

```
$ python tests/test_indexer.py
OpenJDK 64-Bit Server VM warning: Cannot open file logs/gc.log due to No such file or directory

WARNING:elasticsearch:PUT http://localhost:53520/dss-dev-aws-docs-f674ee64724be9aca6f34adcdaf4882902935d43-test_alias_and_versioned_index_exists-testawsindexer [status:400 request:0.116s]
ERROR:dss.index.es.manager:Unable to create index: dss-dev-aws-docs-f674ee64724be9aca6f34adcdaf4882902935d43-test_alias_and_versioned_index_exists-testawsindexer Exception: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dss-dev-aws-docs-f674ee64724be9aca6f34adcdaf4882902935d43-test_alias_and_versioned_index_exists-testawsindexer] as the final mapping would have more than 1 type: [query, doc]')
WARNING:dss.index.es.backend:An exception occurred in retry.TX(name='index', {'bundle': BundleDocument(replica=Replica.aws, fqid=07bc3e09-1311-4402-8ada-dd5850d308bb.2019-09-23T204827.680899Z, {'manifest': {'format': '0.0.1', 'version': '2019-09-23T204827.680899Z', 'files': [{'name': 'cell_suspension_0.json', 'uuid': 'edcebb4e-6604-401f-bb31-97009e9ecdcc', 'version': '2019-09-23T204836.996181Z', 'content-type': 'application/json', 'size': 430, 'indexed': True, 'crc32c': '33644068', 's3-etag': '91e67067d63c944a1d028754b80c8a7b', 'sha1': '2b538add4a44d0b3e5b7e6f80a2e84bb3f42c02c', 'sha256': '5c4d9fe9957f1a5d6dff22ce63656e0f29f8d2a13ab8e853c5c56e1130ca6f75'}, {'name': 'dissociation_protocol_0.json', 'uuid': 'e27a13ff-be69-4663-85ce-8a4405da053b', 'version': '2019-09-23T204841.125849Z', 'content-type': 'application/json', 'size': 561, 'indexed': True, 'crc32c': 'ecc1d83b', 's3-etag': '0f7b9f99e4619885270ad721e12106cf', 'sha1': '22800b9bb5e6af88567e6f285451424a65d48be4', 'sha256': '043a50ba97100017145202802c5dd469a1c503399bad1a27865e355f0c554c51'}, {'name': 'donor_organism_0.json', 'uuid': '4c605173-d408-4e06-b28c-dc2325223e10', 'version': '2019-09-23T204842.521701Z', 'content-type': 'application/json', 'size': 644, 'indexed': True, 'crc32c': 'a262027c', 's3-etag': '1284b0a2f7978d8e2183707fc2a541e1', 'sha1': '885266daae0a0b9217e800f3f3932cead0156de6', 'sha256': '15789c6c43dfaa44b1a09d581f5e72a90d8d2cf3774a63a07f397c2c8c46ac1f'}, {'name': 'enrichment_protocol_0.json', 'uuid': 'de8bdb17-7ecd-4ee0-9182-d8c1d1866d9b', 'version': '2019-09-23T204843.915156Z', 'content-type': 'application/json', 'size': 498, 'indexed': True, 'crc32c': 'd202912e', 's3-etag': '5f888ab720b8e9900e0a4a11310e5ced', 'sha1': '7be99c8c9b5b05329f70b159dabe91f0140d95a6', 'sha256': '0ea055514a90a3b9f659b160f29d3a75722fd51bc73f39c1be3107d2df4edf8d'}, {'name': 'library_preparation_protocol_0.json', 'uuid': '190d4713-ae51-49e8-9708-c46bfe46c106', 'version': '2019-09-23T204845.379861Z', 'content-type': 'application/json', 'size': 607, 'indexed': True, 'crc32c': '0246640b', 's3-etag': 'e2a7ed5a068107fcc2723caaefa736c4', 'sha1': 'd89c0681319030541c19cef449e60167109b242a', 'sha256': 'ba3f57ce072ef195de176d78c4d1390bd4c02fda58c1acbf59f0655b5a2c7574'}, {'name': 'links.json', 'uuid': 'eedaa6f2-25f3-45ef-9af8-614af7c9b8b6', 'version': '2019-09-23T204846.827853Z', 'content-type': 'application/json', 'size': 1702, 'indexed': True, 'crc32c': '9aba2ad7', 's3-etag': '4df7186f2435bd20aaf7654f2508bd0e', 'sha1': '510017f5ef22045c956cff10179be88ce54caaea', 'sha256': 'f4a5b0b66e8bbe2edee79098e5be958f22867693eb1be09cb3ebd5b0525eec5f'}, {'name': 'process_0.json', 'uuid': '541a3b16-3ece-4cec-8b69-6dfa61e7e83e', 'version': '2019-09-23T204848.393785Z', 'content-type': 'application/json', 'size': 360, 'indexed': True, 'crc32c': 'f4838412', 's3-etag': 'aa86bb311d3561646a32fcf15f797f5e', 'sha1': 'ffefcb7fbffc1f1448328a8bf5e7cf93d2844c49', 'sha256': 'ddca505d8a6d01cfd5661b344c9270e4e40c561c031b38ac330cabf2644c6859'}, {'name': 'process_1.json', 'uuid': 'c8ae53be-c45e-4229-91f8-696aa2445bf6', 'version': '2019-09-23T204850.103831Z', 'content-type': 'application/json', 'size': 349, 'indexed': True, 'crc32c': 'ef9b6d00', 's3-etag': '7fd337340c3d3e8ae193810cc503d83a', 'sha1': '6d5448c64413ff748632cb47da467d0eb73d61a1', 'sha256': '24ea2c4257aa029c4e1f7dff31138a5e668a951384ceb344c05f10f8fc564b6e'}, {'name': 'process_2.json', 'uuid': 'de356313-0d7b-4a8d-b1b9-a9a9d1d68251', 'version': '2019-09-23T204851.516644Z', 'content-type': 'application/json', 'size': 349, 'indexed': True, 'crc32c': '8f84ca77', 's3-etag': '4e421ac770ce83ef06de2c23bf64504a', 'sha1': '8b6c6874f6a9a9a57c11ad3e8b34adeb82bb6331', 'sha256': '850ab01505fdfbb96138a68438e1ca60fbde3a551d9715b231c39f138f35132e'}, {'name': 'project_0.json', 'uuid': '35de1fd1-c938-4f58-a72d-81bd159d268f', 'version': '2019-09-23T204852.850201Z', 'content-type': 'application/json', 'size': 3312, 'indexed': True, 'crc32c': 'f0e64851', 's3-etag': 'c8e60ace71fd7622217b14527b1d5f82', 'sha1': '194e723f6441e293c0363441446913c2598fae5c', 'sha256': '2f6350d90363747ba464f1b6bdfce7c6c0a5983941f349e53a330990dd2c1440'}, {'name': 'sequence_file_0.json', 'uuid': 'ee7026c7-fbb9-4ca8-9cee-e354494a3a94', 'version': '2019-09-23T204854.341066Z', 'content-type': 'application/json', 'size': 419, 'indexed': True, 'crc32c': '6a1a7f35', 's3-etag': '0fbacffdcf806792d3e6061ce6a25062', 'sha1': 'bcbca1ae7ea842c013064c909c45f6f63ad57a74', 'sha256': '6a54af2e777ca88ebc030d9905214a8172b9da1f9e888daf75b4f3b177592b56'}, {'name': 'sequence_file_1.json', 'uuid': 'ccbf2262-9096-4609-99f5-fdff2c1adfce', 'version': '2019-09-23T204855.945916Z', 'content-type': 'application/json', 'size': 419, 'indexed': True, 'crc32c': 'f8759c6f', 's3-etag': '91a9c99105605821f6d88205ff932a65', 'sha1': 'f718753375f4714e748175fc42d3bcd55cbc8fb7', 'sha256': '0e48fdc80be7d661268c38383f770cfdeaa9978d8670a9231ae9950669811b85'}, {'name': 'sequencing_protocol_0.json', 'uuid': '39eb9f32-7bae-4379-af4f-b7b153e661ad', 'version': '2019-09-23T204857.366583Z', 'content-type': 'application/json', 'size': 586, 'indexed': True, 'crc32c': '12227ca1', 's3-etag': 'ffdf31ccfc03352b171049a4edbfac5c', 'sha1': 'ca8c9f2b8e65eae2899aaeac4f03c8e76608e1d9', 'sha256': '1cbba5403b47877e3d81dcfc9b61dc029de65ddc532f3170d8bd1568b27d0839'}, {'name': 'specimen_from_organism_0.json', 'uuid': 'cbbfd50f-9074-4c01-82d9-07ecb8e4820c', 'version': '2019-09-23T204859.085651Z', 'content-type': 'application/json', 'size': 811, 'indexed': True, 'crc32c': 'dd9996dc', 's3-etag': '5e5a9b577c6cbd01acd82ca23a6d1050', 'sha1': '15deb9c4e7cf59b3e2dae39ae0a0a1ee3c5650d7', 'sha256': 'b5db6991a0b619c02b5dcaaadb342564130230a76fa2e2c940d5193076c35460'}, {'name': 'text_data_file1.txt', 'uuid': '586a3fb1-8d96-400b-bbdf-e58051fa19cc', 'version': '2019-09-23T204904.007430Z', 'content-type': 'text/plain', 'size': 61, 'indexed': False, 'crc32c': '63e0d311', 's3-etag': 'f608d24d56908f904ab91b2d6655a37a', 'sha1': '610200a86b4cbd67880ade3d4a6aa213b0207beb', 'sha256': '017aeb0676d03fdce0aeb46020f4b038650858ce018056f18c1b0106080351a6'}, {'name': 'text_data_file2.txt', 'uuid': 'b45dba26-449f-4b96-b9a9-eb8196efc13f', 'version': '2019-09-23T204905.435886Z', 'content-type': 'text/plain', 'size': 61, 'indexed': False, 'crc32c': '63e0d311', 's3-etag': 'f608d24d56908f904ab91b2d6655a37a', 'sha1': '610200a86b4cbd67880ade3d4a6aa213b0207beb', 'sha256': '017aeb0676d03fdce0aeb46020f4b038650858ce018056f18c1b0106080351a6'}], 'creator_uid': 1234}, 'state': 'new', 'files': defaultdict(<class 'list'>, {'cell_suspension_json': [{'describedBy': 'https://schema.humancellatlas.org/type/biomaterial/6.1.1/cell_suspension', 'schema_type': 'biomaterial', 'biomaterial_core': {'biomaterial_id': 'Q4_DEMO-cellsus_SAMN02797092', 'ncbi_taxon_id': [9606]}}], 'dissociation_protocol_json': [{'describedBy': 'https://schema.humancellatlas.org/type/protocol/biomaterial_collection/2.0.0/dissociation_protocol', 'schema_type': 'protocol', 'protocol_core': {'protocol_id': 'dissociation_1', 'protocol_name': 'a FACS method to separate cells'}, 'dissociation_method': {'text': 'fluorescence-activated cell sorting', 'ontology': 'EFO:0009108'}}], 'donor_organism_json': [{'describedBy': 'https://schema.humancellatlas.org/type/biomaterial/5.2.1/donor_organism', 'schema_type': 'biomaterial', 'biomaterial_core': {'biomaterial_id': 'Q4_DEMO-donor_MGH30', 'biomaterial_name': 'Q4 DEMO donor MGH30', 'ncbi_taxon_id': [9606]}, 'medical_history': {'smoking_history': 'yes'}, 'genus_species': [{'text': 'Homo sapiens'}], 'is_living': False, 'biological_sex': 'unknown'}], 'enrichment_protocol_json': [{'describedBy': 'https://schema.humancellatlas.org/type/protocol/biomaterial_collection/2.0.0/enrichment_protocol', 'schema_type': 'protocol', 'protocol_core': {'protocol_id': 'enrichment1'}, 'enrichment_method': {'text': 'fluorescence-activated cell sorting', 'ontology': 'EFO:0009108'}}], 'library_preparation_protocol_json': [{'describedBy': 'https://schema.humancellatlas.org/type/protocol/sequencing/3.0.0/library_preparation_protocol', 'schema_type': 'protocol', 'protocol_core': {'protocol_id': 'preparation1'}, 'input_nucleic_acid_molecule': {'text': 'polyA RNA'}, 'library_construction_approach': {'text': 'Smart-seq2', 'ontology': 'EFO:0008931'}, 'end_bias': '5 prime end bias', 'strand': 'unstranded'}], 'links_json': [{'describedBy': 'http://schema.dev.data.humancellatlas.org/system/1.1.1/links', 'schema_type': 'link_bundle', 'schema_version': '1.1.1', 'links': [{'process': 'fae5415a-7a16-433b-882b-399c0f5efe34', 'inputs': ['cb5b6f2b-8561-4cfa-96f0-ca1dda3b661c'], 'input_type': 'biomaterial', 'outputs': ['c2c44dd4-7fb3-410e-a765-37c6331e97b4', '78971d24-b317-4f5b-9c95-e606905414ab'], 'output_type': 'file', 'protocols': [{'protocol_type': 'library_preparation_protocol', 'protocol_id': '6603e237-9f5d-4a40-88b8-8df65474a794'}, {'protocol_type': 'sequencing_protocol', 'protocol_id': '67b7bddf-c0bf-42da-b3ee-804073b26269'}]}, {'process': '7ead592c-32d6-4a89-8e2c-471a46436ee0', 'inputs': ['bc707c41-cd66-4540-9f69-e5fed3ba6459'], 'input_type': 'biomaterial', 'outputs': ['cb5b6f2b-8561-4cfa-96f0-ca1dda3b661c'], 'output_type': 'biomaterial', 'protocols': [{'protocol_type': 'dissociation_protocol', 'protocol_id': '500215c8-7877-4e20-8b30-e3820bd098e4'}, {'protocol_type': 'enrichment_protocol', 'protocol_id': 'd2d57618-fa80-4b98-8c76-3c96b76c44bf'}]}, {'process': 'a3400037-be42-41c3-9605-d094472646d6', 'inputs': ['dcbe0115-7871-41de-8502-b68f6ca024ab'], 'input_type': 'biomaterial', 'outputs': ['bc707c41-cd66-4540-9f69-e5fed3ba6459'], 'output_type': 'biomaterial', 'protocols': []}]}], 'process_json': [{'process_core': {'process_id': 'sequence_process_file_1'}, 'schema_type': 'process', 'describedBy': 'https://schema.humancellatlas.org/type/process/2.1.1/process'}, {'process_core': {'process_id': 'process_id_2'}, 'schema_type': 'process', 'describedBy': 'https://schema.humancellatlas.org/type/process/2.1.1/process'}, {'process_core': {'process_id': 'process_id_1'}, 'schema_type': 'process', 'describedBy': 'https://schema.humancellatlas.org/type/process/2.1.1/process'}], 'project_json': [{'describedBy': 'https://schema.humancellatlas.org/type/project/5.2.1/project', 'schema_type': 'project', 'project_core': {'project_shortname': 'Q4_DEMO-project_PRJNA248302', 'project_title': 'Q4_DEMO-Single cell RNA-seq of primary human glioblastomas', 'project_description': 'Q4_DEMO-We report transcriptomes from 430 single glioblastoma cells isolated from 5 individual tumors and 102 single cells from gliomasphere cells lines generated using SMART-seq. In addition, we report population RNA-seq from the five tumors as well as RNA-seq from cell lines derived from 3 tumors (MGH26, MGH28, MGH31) cultured under serum free (GSC) and differentiated (DGC) conditions. This dataset highlights intratumoral heterogeneity with regards to the expression of de novo derived transcriptional modules and established subtype classifiers. Overall design: Operative specimens from five glioblastoma patients (MGH26, MGH28, MGH29, MGH30, MGH31) were acutely dissociated, depleted for CD45+ inflammatory cells and then sorted as single cells (576 samples). Population controls for each tumor were isolated by sorting 2000-10000 cells and processed in parallel (5 population control samples). Single cells from two established cell lines, GBM6 and GBM8, were also sorted as single cells (192 samples). SMART-seq protocol was implemented to generate single cell full length transcriptomes (modified from Shalek, et al Nature 2013) and sequenced using 25 bp paired end reads. Single cell cDNA libraries for MGH30 were resequenced using 100 bp paired end reads to allow for isoform and splice junction reconstruction (96 samples, annotated MGH30L). Cells were also cultured in serum free conditions to generate gliomasphere cell lines for MGH26, MGH28, and MGH31 (GSC) which were then differentiated using 10% serum (DGC). Population RNA-seq was performed on these samples (3 GSC, 3 DGC, 6 total). The initial dataset included 875 RNA-seq libraries (576 single glioblastoma cells, 96 resequenced MGH30L, 192 single gliomasphere cells, 5 tumor population controls, 6 population libraries from GSC and DGC samples). Data was processed as described below using RSEM for quantification of gene expression. 5,948 genes with the highest composite expression either across all single cells combined (average log2(TPM)>4.5) or within a single tumor (average log2(TPM)>6 in at least one tumor) were included. Cells expressing less than 2,000 of these 5,948 genes were excluded. The final processed dataset then included 430 primary single cell glioblastoma transcriptomes, 102 single cell transcriptomes from cell lines(GBM6,GBM8), 5 population controls (1 for each tumor), and 6 population libraries from cell lines derived from the tumors (GSC and DGC for MGH26, MGH28 and MGH31). The final matrix (GBM_data_matrix.txt) therefore contains 5948 rows (genes) quantified in 543 samples (columns). Please note that the samples which are not included in the data processing are indicated in the sample description field.'}, 'contributors': [{'contact_name': 'Q4_DEMO-MintTeam', 'email': 'dummy@email.com'}]}], 'sequence_file_json': [{'describedBy': 'https://schema.humancellatlas.org/type/file/6.1.1/sequence_file', 'schema_type': 'file', 'file_core': {'file_name': 'R1.fastq.gz', 'file_format': 'fastq.gz'}, 'read_index': 'read1', 'lane_index': 1}, {'describedBy': 'https://schema.humancellatlas.org/type/file/6.1.1/sequence_file', 'schema_type': 'file', 'file_core': {'file_name': 'R2.fastq.gz', 'file_format': 'fastq.gz'}, 'read_index': 'read2', 'lane_index': 1}], 'sequencing_protocol_json': [{'describedBy': 'https://schema.humancellatlas.org/type/protocol/sequencing/7.0.0/sequencing_protocol', 'schema_type': 'protocol', 'protocol_core': {'protocol_id': 'assay_1'}, 'instrument_manufacturer_model': {'text': 'Illumina HiSeq 2500'}, 'paired_ends': True, 'sequencing_approach': {'text': 'full length single cell RNA sequencing', 'ontology': 'EFO:0008441'}}], 'specimen_from_organism_json': [{'describedBy': 'https://schema.humancellatlas.org/type/biomaterial/5.2.2/specimen_from_organism', 'schema_type': 'biomaterial', 'biomaterial_core': {'biomaterial_id': 'Q4_DEMO-sample_SAMN02797092', 'biomaterial_name': 'Q4_DEMO-Single cell mRNA-seq_MGH30_A01', 'ncbi_taxon_id': [9606], 'supplementary_files': ['Q4_DEMO-protocol']}, 'genus_species': [{'text': 'Homo sapiens'}], 'organ': {'text': 'brain'}, 'organ_part': {'text': 'astrocyte'}, 'disease': [{'text': 'glioblastoma'}], 'collection_time': '2018-07-22'}]}), 'uuid': '07bc3e09-1311-4402-8ada-dd5850d308bb', 'shape_descriptor': 'v.cell_suspension.6.dissociation_protocol.2.donor_organism.5.enrichment_protocol.2.library_preparation_protocol.3.links.1.process.2.project.5.sequence_file.6.sequencing_protocol.7.specimen_from_organism.5'})}).
Traceback (most recent call last):
  File "/Users/charles/codes/data-store4/dss/util/retry.py", line 207, in wrapper
    return f(*args, **kwargs)
  File "/Users/charles/codes/data-store4/dss/index/es/document.py", line 155, in index
    index_name = self._prepare_index(dryrun)
  File "/Users/charles/codes/data-store4/dss/index/es/document.py", line 223, in _prepare_index
    IndexManager.create_index(es_client, self.replica, index_name)
  File "/Users/charles/codes/data-store4/dss/index/es/manager.py", line 23, in create_index
    cls.create_doc_index(es_client, index_name, alias_name, index_mapping)
  File "/Users/charles/codes/data-store4/dss/index/es/manager.py", line 35, in create_doc_index
    raise ex
  File "/Users/charles/codes/data-store4/dss/index/es/manager.py", line 31, in create_doc_index
    response = es_client.indices.create(index_name, body=index_mapping)
  File "/Users/charles/codes/data-store4/vp/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/charles/codes/data-store4/vp/lib/python3.6/site-packages/elasticsearch/client/indices.py", line 107, in create
    params=params, body=body)
  File "/Users/charles/codes/data-store4/vp/lib/python3.6/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/Users/charles/codes/data-store4/vp/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 129, in perform_request
    self._raise_error(response.status, raw_data)
  File "/Users/charles/codes/data-store4/vp/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dss-dev-aws-docs-f674ee64724be9aca6f34adcdaf4882902935d43-test_alias_and_versioned_index_exists-testawsindexer] as the final mapping would have more than 1 type: [query, doc]')
Stack (most recent call last):
  File "/Users/charles/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/Users/charles/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/charles/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/charles/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/concurrent/futures/thread.py", line 69, in _worker
    work_item.run()
  File "/Users/charles/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/charles/codes/data-store4/dss/util/retry.py", line 207, in wrapper
    return f(*args, **kwargs)
  File "/Users/charles/codes/data-store4/dss/index/es/backend.py", line 45, in index_bundle
    modified, index_name = doc.index(dryrun=self.dryrun)
  File "/Users/charles/codes/data-store4/dss/util/retry.py", line 209, in wrapper
    tx.log_exception(e)
  File "/Users/charles/codes/data-store4/dss/util/retry.py", line 282, in log_exception
    self.logger.warning("An exception occurred in %r.", self, exc_info=True, stack_info=True)
WARNING:dss.index.es.backend:Exception 'TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dss-dev-aws-docs-f674ee64724be9aca6f34adcdaf4882902935d43-test_alias_and_versioned_index_exists-testawsindexer] as the final mapping would have more than 1 type: [query, doc]')' occurred in retry.TX(name='index_bundle', {'bundle': <dss.index.bundle.Bundle object at 0x106a30b00>}). The back trace was logged earlier.
ERROR:dss.index.indexer:Exception occurred while processing Replica.aws event: bundles/07bc3e09-1311-4402-8ada-dd5850d308bb.2019-09-23T204827.680899Z
Traceback (most recent call last):
  File "/Users/charles/codes/data-store4/dss/index/indexer.py", line 33, in process_new_indexable_object
    self.index_object(key)
  File "/Users/charles/codes/data-store4/dss/index/indexer.py", line 47, in index_object
    self._index_bundle(identifier)
  File "/Users/charles/codes/data-store4/dss/index/indexer.py", line 65, in _index_bundle
    self.backend.index_bundle(bundle)
  File "/Users/charles/codes/data-store4/dss/index/backend.py", line 95, in index_bundle
    self._delegate(self.index_bundle.__name__, args, kwargs)
  File "/Users/charles/codes/data-store4/dss/index/backend.py", line 121, in _delegate
    raise RuntimeError(f"One or more backends failed: {problems}")
RuntimeError: One or more backends failed: ["Backend ElasticsearchIndexBackend(dryrun=False, notify=None) raised an exception: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dss-dev-aws-docs-f674ee64724be9aca6f34adcdaf4882902935d43-test_alias_and_versioned_index_exists-testawsindexer] as the final mapping would have more than 1 type: [query, doc]')"]
EWARNING:elasticsearch:PUT http://localhost:53520/dss-dev-aws-docs-f674ee64724be9aca6f34adcdaf4882902935d43-test_create-testawsindexer [status:400 request:0.013s]
ERROR:dss.index.es.manager:Unable to create index: dss-dev-aws-docs-f674ee64724be9aca6f34adcdaf4882902935d43-test_create-testawsindexer Exception: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dss-dev-aws-docs-f674ee64724be9aca6f34adcdaf4882902935d43-test_create-testawsindexer] as the final mapping would have more than 1 type: [query, doc]')
```

## Steps to reproduce the behavior

Install elasticsearch (on Mac):

```
brew install elasticsearch
```

Then run the indexer test:

```
source environment
python tests/test_indexer.py
```

**Comment by chmreid** [comment]
I was missing two local environment variable values in my local environment file:
- `DSS_ES_PORT=9200`
- `DSS_TEST_ES_PATH="/usr/local/bin/elasticsearch"

Two more that may be used when running local tests (or, maybe just by terraform):
- `DSS_ES_VOLUME_SIZE="35"`
- `DSS_ES_INSTANCE_COUNT="1"`

Solution was to put these in an environment file called `environment.es` and then run `source environment && source environment.es`

**Comment by xbrianh** [comment]
@chmreid For these kinds of issues, it's often helpful to look at the configuration of the CI/CD environment. For instance, the local elasticsearch executable and environment is [configured here](https://github.com/HumanCellAtlas/data-store/blob/69d412cfc1ecd2c83dfdb597b276f024dcbee3a7/allspark.Dockerfile#L56-L59).

**Comment by chmreid** [comment]
Was still seeing these errors even after trying the fixes above. Turns out Elasticsearch 6 introduced changes that broke multiple mappings (see [Breaking changes in Elasticsearch 6.0](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/breaking-changes-6.0.html)), which is what these errors are all about.

Had to install Elasticsearch version 5.6.16 via homebrew with this command:

```
brew install elasticsearch@5.6
```

**Comment by chmreid** [comment]
Not quite so easy, apparently. Now elasticsearch5 won't start:

```
$ elasticsearch
Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: org.apache.lucene.index.IndexFormatTooNewException: Format version is not supported (resource BufferedChecksumIndexInput(SimpleFSIndexInput(path="/usr/local/etc/elasticsearch/elasticsearch.keystore"))): 4 (needs to be between 1 and 2)
Likely root cause: org.apache.lucene.index.IndexFormatTooNewException: Format version is not supported (resource BufferedChecksumIndexInput(SimpleFSIndexInput(path="/usr/local/etc/elasticsearch/elasticsearch.keystore"))): 4 (needs to be between 1 and 2)
	at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:216)
	at org.apache.lucene.codecs.CodecUtil.checkHeader(CodecUtil.java:198)
	at org.elasticsearch.common.settings.KeyStoreWrapper.load(KeyStoreWrapper.java:175)
	at org.elasticsearch.bootstrap.Bootstrap.loadSecureSettings(Bootstrap.java:246)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:304)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84)
Refer to the log for complete error details.
```

**Comment by chmreid** [comment]
It seems that the Elasticsearch5 installation from Homebrew is borked, and Homebrew does not offer much flexibility to specify which version of Elasticsearch is installed (only version 5.6.16 or the latest version).

To install elasticsearch 5.4.2 (or whichever version) manually:

- install Java (preferably using brew)
- download elasticsearch 5.4.2 from here: https://www.elastic.co/downloads/past-releases/elasticsearch-5-4-2
    - any other version of elasticsearch x.y.z is available at https://www.elastic.co/downloads/past-releases/elasticsearch-x-y-z
- extract elasticsearch 5.4.2 to wherever you want the final elasticsearch binary to live (example: `$HOME/pkg`)
- set `ES_HOME` to the directory where you extracted elasticsearch 5.4.2
    - example: `export ES_HOME="$HOME/pkg/elasticsearch-5.4.2"`
- set `JAVA_HOME` to the directory where your Java binary lives
    - example: `export JAVA_HOME="/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home"`
- set `PATH` to include both of these directories at the front of the path
    - example: `export PATH=$ES_HOME/bin:$JAVA_HOME/bin:$PATH`

Now start a new shell and run `elasticsearch` and it should run version 5.4.2.
