### ISSUE TITLE
Blank Subv2 break notifications.

### ISSUE THREAD

**Issue by amarjandu** [HumanCellAtlas/data-store#2520]
v2 Subscriptions with blank bodies enter the DDB table, this causes yield errors that will break notifications, as well as subscription retrieval. 

```
$ python tests/test_notify_v2.py
INFO:dss:Flask debug is disabled.
ssWARNING:daemons.dss-notify-v2.app:Key bundles/uuid.version not found in replica aws, unable to notify uuid
WARNING:daemons.dss-notify-v2.app:Key bundles/uuid.version not found in replica aws, unable to notify uuid
WARNING:daemons.dss-notify-v2.app:Key bundles/uuid.version not found in replica gcp, unable to notify uuid
WARNING:daemons.dss-notify-v2.app:Key bundles/uuid.version not found in replica gcp, unable to notify uuid
.s.sssssssE
======================================================================
ERROR: tearDownClass (__main__.TestNotifyV2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_notify_v2.py", line 85, in tearDownClass
    subs = [s for s in get_subscriptions_for_owner(replica, cls.owner) if s['owner'] == cls.owner]
  File "/Users/charles/codes/data-store4/dss/subscriptions_v2/__init__.py", line 77, in get_subscriptions_for_owner
    return [json.loads(item) for item in items]
  File "/Users/charles/codes/data-store4/dss/subscriptions_v2/__init__.py", line 77, in <listcomp>
    return [json.loads(item) for item in items]
  File "/Users/charles/codes/data-store4/dss/dynamodb/__init__.py", line 84, in get_primary_key_items
    yield item[return_key]['S']
KeyError: 'body'

----------------------------------------------------------------------
Ran 12 tests in 2.406s

FAILED (errors=1, skipped=10)
```

**Comment by amarjandu** [comment]
This issue seems to be specific to a dev version of subscription stats, moving testing to platform-hca, issue might be with how notify-v2 deamon sends items to the notification queue from the subscription
