### ISSUE TITLE
Checkout operation bug.

### ISSUE THREAD

**Issue by DailyDreaming** [HumanCellAtlas/data-store#2547]
Writing a fix now.

```
(v3nv) quokka@qcore:~/checkout/data-store$ python scripts/dss-ops.py checkout verify --replica=aws --keys=files/e0402d5e-a1c0-42f2-8eba-2e9462418d22
WARNING:dss.operations.checkout:Unable to locate: org-humancellatlas-dss-dev/files/e0402d5e-a1c0-42f2-8eba-2e9462418d22
ERROR:dss.operations:Traceback (most recent call last):
  File "/home/quokka/checkout/data-store/dss/operations/__init__.py", line 106, in __call__
    action_handler(argv, args)
  File "/home/quokka/checkout/data-store/dss/operations/checkout.py", line 89, in __call__
    self.process_keys()
  File "/home/quokka/checkout/data-store/dss/operations/checkout.py", line 154, in process_keys
    blob_key = compose_blob_key(file_metadata)
  File "/home/quokka/checkout/data-store/dss/storage/hcablobstore/__init__.py", line 105, in compose_blob_key
    file_info[FileMetadata.SHA256],
TypeError: 'NoneType' object is not subscriptable
```

**Comment by chmreid** [comment]
@DailyDreaming Which stage were you on when you ran these commands? w.r.t. 1 and 2, I can't reproduce these errors, the `_get_metadata()` method returns nothing so the error is caught before it crashes:

```
$ python ./scripts/dss-ops.py checkout verify --replica=aws --keys=files/e0402d5e-a1c0-42f2-8eba-2e9462418d22
{
  "replica": "aws"
}
Unable to locate: org-humancellatlas-dss-dev/files/e0402d5e-a1c0-42f2-8eba-2e9462418d22Key not in either main bucket or checkout bucket: files/e0402d5e-a1c0-42f2-8eba-2e9462418d22

$ python ./scripts/dss-ops.py checkout verify --replica=aws --keys=files/0040a691-ceb0-4ebf-96f5-eb83f0f96ced.2019-10-28T193940.055487Z
{
  "replica": "aws"
}
Unable to locate: org-humancellatlas-dss-dev/files/0040a691-ceb0-4ebf-96f5-eb83f0f96ced.2019-10-28T193940.055487ZKey not in either main bucket or checkout bucket: files/0040a691-ceb0-4ebf-96f5-eb83f0f96ced.2019-10-28T193940.055487Z
```

w.r.t. 3, I don't have a `checkout start` action available?

```
$ ./scripts/dss-ops.py checkout start --replica aws --keys files/be15f4a9-7513-4620-9c1b-87534cb278e6.2019-07-03T083148.453000Z
usage: dss-ops.py checkout [-h] {remove,verify,add,sync} ...
dss-ops.py checkout: error: invalid choice: 'start' (choose from 'remove', 'verify', 'add', 'sync')
```

Can help write tests once I'm able to reproduce these.

**Comment by chmreid** [comment]
I'm still blocked on this ticket
