### ISSUE TITLE
Prod token interpretation.

### ISSUE THREAD

**Issue by DailyDreaming** [HumanCellAtlas/data-store#2608]
```
(v3nv) quokka@qcore:~$ hca dss get-collections
Traceback (most recent call last):
  File "/home/quokka/data-store/v3nv/bin/hca", line 10, in <module>
    sys.exit(main())
  File "/home/quokka/data-store/v3nv/lib/python3.6/site-packages/hca/cli.py", line 131, in main
    result = parsed_args.entry_point(parsed_args)
  File "/home/quokka/data-store/v3nv/lib/python3.6/site-packages/hca/util/__init__.py", line 161, in _cli_call
    return self._consume_response(self._request(vars(cli_args)))
  File "/home/quokka/data-store/v3nv/lib/python3.6/site-packages/hca/util/__init__.py", line 146, in _request
    raise SwaggerAPIException(response=res)
hca.util.exceptions.SwaggerAPIException: None: None (HTTP 403). Details:
{"message":"'eyJ0eXAsomethingsomethingyuSYC_kmcWvQA' not a valid key=value pair (missing equal-sign) in Authorization header: 'Bearer eyJ0eXAsomethingsomethingiOiJKV1QiLCJhbGc"}```

**Comment by DailyDreaming** [comment]
Closing in favor of: https://github.com/HumanCellAtlas/dcp-cli/issues/493
