### ISSUE TITLE
Smoketest: Error in bundle registration

### ISSUE THREAD

**Issue by kislyuk** [HumanCellAtlas/data-store#444]
```
hca upload --replica aws --staging-bucket $DSS_S3_BUCKET_TEST --file-or-dir data-bundle-examples/10X_v2/pbmc8k > upload.json
```
```
Uploading the following keys to aws:
assay.json
large_file
large_file.zip
manifest.json
project.json
sample.json
The following keys were uploaded successfully:
assay.json    70696c65-76a0-429f-b6ff-1aaaa76ad2cd/assay.json
large_file    a90a20a6-8b9d-4ab6-986b-71892361fb54/large_file
large_file.zip  d7f2411e-2b70-43fb-ac0b-52fef5a81f9b/large_file.zip
manifest.json  963a4711-1127-4029-88d2-1b53384462e5/manifest.json
project.json  ba87d228-2c96-4960-8dfb-2019344c75e7/project.json
sample.json   25163620-a47c-4673-8690-d9115989fc8a/sample.json
File assay.json: registering...
s3://org-humancellatlas-dss-test/70696c65-76a0-429f-b6ff-1aaaa76ad2cd/assay.json
File assay.json: assigned uuid 70696c65-76a0-429f-b6ff-1aaaa76ad2cd
File assay.json: registered with uuid 70696c65-76a0-429f-b6ff-1aaaa76ad2cd
Request response
{
  "version": "2017-09-12T160038.719343Z"
}

File large_file: registering...
s3://org-humancellatlas-dss-test/a90a20a6-8b9d-4ab6-986b-71892361fb54/large_file
File large_file: assigned uuid a90a20a6-8b9d-4ab6-986b-71892361fb54
File large_file: registered with uuid a90a20a6-8b9d-4ab6-986b-71892361fb54
Request response
{
  "task_id": "0fa73c5c-f5b4-4369-ae43-1ff2f18dea89",
  "version": "2017-09-12T160040.125907Z"
}

File large_file.zip: registering...
s3://org-humancellatlas-dss-test/d7f2411e-2b70-43fb-ac0b-52fef5a81f9b/large_file.zip
File large_file.zip: assigned uuid d7f2411e-2b70-43fb-ac0b-52fef5a81f9b
File large_file.zip: registered with uuid d7f2411e-2b70-43fb-ac0b-52fef5a81f9b
Request response
{
  "task_id": "8a4f9e08-5e66-43c1-b360-326ccc3379ce",
  "version": "2017-09-12T160043.373133Z"
}

File manifest.json: registering...
s3://org-humancellatlas-dss-test/963a4711-1127-4029-88d2-1b53384462e5/manifest.json
File manifest.json: assigned uuid 963a4711-1127-4029-88d2-1b53384462e5
File manifest.json: registered with uuid 963a4711-1127-4029-88d2-1b53384462e5
Request response
{
  "version": "2017-09-12T160046.065427Z"
}

File project.json: registering...
s3://org-humancellatlas-dss-test/ba87d228-2c96-4960-8dfb-2019344c75e7/project.json
File project.json: assigned uuid ba87d228-2c96-4960-8dfb-2019344c75e7
File project.json: registered with uuid ba87d228-2c96-4960-8dfb-2019344c75e7
Request response
{
  "version": "2017-09-12T160046.985390Z"
}

File sample.json: registering...
s3://org-humancellatlas-dss-test/25163620-a47c-4673-8690-d9115989fc8a/sample.json
File sample.json: assigned uuid 25163620-a47c-4673-8690-d9115989fc8a
File sample.json: registered with uuid 25163620-a47c-4673-8690-d9115989fc8a
Request response
{
  "version": "2017-09-12T160048.272579Z"
}

Bundle 97f0f2d2-ffdd-48af-80cb-7cb3f33d1b72: registering...
Bundle 97f0f2d2-ffdd-48af-80cb-7cb3f33d1b72: registration FAILED
{
  "code": "unhandled_exception",
  "stacktrace": "Traceback (most recent call last):\n  File \"/var/task/chalicelib/dss/blobstore/s3.py\", line 103, in get\n    Key=object_name\n  File \"/var/task/botocore/client.py\", line 312, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/var/task/botocore/client.py\", line 601, in _make_api_call\n    raise error_class(parsed_response, operation_name)\nbotocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/var/task/chalicelib/dss/error.py\", line 31, in wrapper\n    return func(*args, **kwargs)\n  File \"/var/task/chalicelib/dss/api/bundles.py\", line 128, in put\n    file['file_metadata'] = json.loads(handle.get(bucket, metadata_path))\n  File \"/var/task/chalicelib/dss/blobstore/s3.py\", line 108, in get\n    raise BlobNotFoundError(ex)\ndss.blobstore.BlobNotFoundError: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.\n",
  "status": 500,
  "title": "An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist."
}
Traceback (most recent call last):
  File "/Users/akislyuk/projects/data-store/v3/bin/hca", line 11, in <module>
    hca.main()
  File "/Users/akislyuk/projects/data-store/v3/lib/python3.6/site-packages/hca/__init__.py", line 25, in main
    response = cli.make_request(sys.argv[1:])
  File "/Users/akislyuk/projects/data-store/v3/lib/python3.6/site-packages/hca/cli.py", line 63, in make_request
    return command.run_from_cli(args)
  File "/Users/akislyuk/projects/data-store/v3/lib/python3.6/site-packages/hca/api/composite_commands/upload.py", line 192, in run_from_cli
    return cls.run(args)
  File "/Users/akislyuk/projects/data-store/v3/lib/python3.6/site-packages/hca/api/composite_commands/upload.py", line 210, in run
    final_return = cls._put_bundle(bundle_uuid, files, args["replica"])
  File "/Users/akislyuk/projects/data-store/v3/lib/python3.6/site-packages/hca/api/composite_commands/upload.py", line 175, in _put_bundle
    response.raise_for_status()
  File "/Users/akislyuk/projects/data-store/v3/lib/python3.6/site-packages/requests/models.py", line 929, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://dss.dev.data.humancellatlas.org/v1/bundles/97f0f2d2-ffdd-48af-80cb-7cb3f33d1b72?replica=aws
```

**Comment by kislyuk** [comment]
Error is sporadic.

Unwrapped exception stack trace:
```
Traceback (most recent call last):
  File "/var/task/chalicelib/dss/blobstore/s3.py", line 103, in get
    Key=object_name
  File "/var/task/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/botocore/client.py", line 601, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/chalicelib/dss/error.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/var/task/chalicelib/dss/api/bundles.py", line 128, in put
    file['file_metadata'] = json.loads(handle.get(bucket, metadata_path))
  File "/var/task/chalicelib/dss/blobstore/s3.py", line 108, in get
    raise BlobNotFoundError(ex)
dss.blobstore.BlobNotFoundError: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
```

**Comment by ttung** [comment]
Interesting, I think this is a race condition. :(
