### ISSUE TITLE
Investigate issues with async copy between accounts/regions

### ISSUE THREAD

**Issue by briandoconnor** [HumanCellAtlas/data-store#470]
Michael and I ran into some permission issues when storing data from a staging bucket in another account/region to the dss we have in Oregon.  This ticket is to investigate this further, we don't have a lot of details right now.

$ bin/storer.py --use-rest-api --bundles s3://org-humancellatlas-data-bundle-examples/import/10x --dss-endpoint https://hca-dss-4.ucsc-cgp-dev.org/v1 --log storer.log

Finding bundles under s3://org-humancellatlas-data-bundle-examples/import/10x...

/import/10x/pbmc8k/bundles/bundle1:
  storing file assay.json as 939d5a8a-55de-4334-ad62-3833b6dc86dd... 2017-09-18T153421.111522Z (2.1 sec, 0.0 MiB/sec)
  storing file project.json as 6bbb0b45-563c-43f4-ab08-d9f8d53a334c... 2017-09-18T153423.258640Z (2.0 sec, 0.0 MiB/sec)
  storing file sample.json as ac51eeaa-3e4b-4ee0-a6b8-e9d2bf3edffe... 2017-09-18T153425.228765Z (1.8 sec, 0.0 MiB/sec)
  storing file pbmc8k_S1_L007_R1_001.fastq.gz (7 GiB) as 384f967f-59c8-4f89-a727-50f404524a12........................................Traceback (most recent call last):
  File "bin/storer.py", line 101, in <module>
    runner = Main()
  File "bin/storer.py", line 63, in __init__
    self._store_bundles(parse_url(self.args.bundles))
  File "bin/storer.py", line 71, in _store_bundles
    self._store_bundle(Url(scheme=bundles_url.scheme, host=bundles_url.host, path=path.lstrip('/')))
  File "bin/storer.py", line 88, in _store_bundle
    BundleStorer(bundle, self.args.dss_endpoint, **self.storer_options).store_bundle()
  File "/Users/mbaumann/Projects/HCA/data-bundle-examples/bin/bundle_tools/storage.py", line 25, in store_bundle
    self._store_files()
  File "/Users/mbaumann/Projects/HCA/data-bundle-examples/bin/bundle_tools/storage.py", line 38, in _store_files
    size=file.size)
  File "/Users/mbaumann/Projects/HCA/data-bundle-examples/bin/bundle_tools/utils.py", line 17, in measure_duration_and_rate
    retval, duration = measure_duration(func, *args)
  File "/Users/mbaumann/Projects/HCA/data-bundle-examples/bin/bundle_tools/utils.py", line 24, in measure_duration
    retval = func(*args)
  File "/Users/mbaumann/Projects/HCA/data-bundle-examples/bin/bundle_tools/storage.py", line 215, in put_file
    return self.driver.put_file(*args, **kwargs)
  File "/Users/mbaumann/Projects/HCA/data-bundle-examples/bin/bundle_tools/storage.py", line 163, in put_file
    response = self._wait_for_file_to_exist(file_uuid)
  File "/Users/mbaumann/Projects/HCA/data-bundle-examples/bin/bundle_tools/storage.py", line 203, in _wait_for_file_to_exist
    raise RuntimeError(f"File {file_uuid} did not appear within {timeout_seconds} seconds")
RuntimeError: File 384f967f-59c8-4f89-a727-50f404524a12 did not appear within 1800 seconds

**Comment by ttung** [comment]
The file is the 7GB file?

Can you see if it eventually succeeded?

Also, it would be helpful to get your cloudwatch logs.

**Comment by kozbo** [comment]
@ttung is this resolved?

**Comment by ttung** [comment]
Yes I believe so.
