### ISSUE TITLE
Elasticsearch timeout occurring during search of deployed DSS

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/data-store#734]
### Expected behavior
Search should complete reliably, without timeouts occurring.

### Actual behavior
Intermittent dcp-cli test failure indicating a timeout in the dev deployment during search:
https://travis-ci.org/HumanCellAtlas/dcp-cli/jobs/311992054
```
======================================================================
ERROR: test_json_input (test.test_dss_cli.TestDssCLI)
Ensure that adding JSON input works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/HumanCellAtlas/dcp-cli/test/test_dss_cli.py", line 62, in test_json_input
    hca.cli.main(args)
  File "/home/travis/build/HumanCellAtlas/dcp-cli/hca/cli.py", line 65, in main
    result = parsed_args.entry_point(parsed_args)
  File "/home/travis/build/HumanCellAtlas/dcp-cli/hca/util/__init__.py", line 139, in _cli_call
    return self._consume_response(self._request(vars(cli_args)))
  File "/home/travis/build/HumanCellAtlas/dcp-cli/hca/util/__init__.py", line 124, in _request
    raise SwaggerAPIException(response=res)
hca.util.exceptions.SwaggerAPIException: internal_server_error: Elasticsearch Internal Server Error (HTTP 500). Details:
Traceback (most recent call last):
  File "/var/task/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/var/task/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/var/lang/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/var/lang/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/var/lang/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/var/lang/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/var/lang/lib/python3.6/ssl.py", line 1002, in recv_into
    return self.read(nbytes, buffer)
  File "/var/lang/lib/python3.6/ssl.py", line 865, in read
    return self._sslobj.read(len, buffer)
  File "/var/lang/lib/python3.6/ssl.py", line 625, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/var/task/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/var/task/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/var/task/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/var/task/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/var/task/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/var/task/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/var/task/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='search-dss-index-dev-wc7kz2vuj7mpfjbxnp4ftplpuu.us-east-1.es.amazonaws.com', port=443): Read timed out. (read timeout=10)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/var/task/elasticsearch/connection/http_requests.py", line 76, in perform_request
    response = self.session.send(prepared_request, **send_kwargs)
  File "/var/task/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/var/task/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='search-dss-index-dev-wc7kz2vuj7mpfjbxnp4ftplpuu.us-east-1.es.amazonaws.com', port=443): Read timed out. (read timeout=10)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/var/task/chalicelib/dss/api/search.py", line 43, in post
    page = _es_search_page(es_query, replica, per_page, _scroll_id, output_format)
  File "/var/task/chalicelib/dss/api/search.py", line 115, in _es_search_page
    sort=sort
  File "/var/task/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/var/task/elasticsearch/client/__init__.py", line 632, in search
    doc_type, '_search'), params=params, body=body)
  File "/var/task/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/var/task/elasticsearch/connection/http_requests.py", line 84, in perform_request
    raise ConnectionTimeout('TIMEOUT', str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeout(HTTPSConnectionPool(host='search-dss-index-dev-wc7kz2vuj7mpfjbxnp4ftplpuu.us-east-1.es.amazonaws.com', port=443): Read timed out. (read timeout=10))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/var/task/chalicelib/dss/error.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/var/task/chalicelib/dss/api/search.py", line 74, in post
    "Elasticsearch Internal Server Error")
dss.error.DSSException
```

**Comment by mikebaumann** [comment]
As suggested by Andrey, try changing the ES instance type to a type which does not use CPU credits. The AWS Elasticsearch console for humancellatlas `dss-index-dev` does show that the CPU credit balance has dropped to zero five times in the past two weeks.
For the AWS Elasticsearch, the supported instance types are available here: http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-supported-instance-types.html

**Comment by Bento007** [comment]
@mikebaumann I believe this has been resolved and should be closed.
