### ISSUE TITLE
ResourceConflictException when deploying visitation Lambda

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#929]
https://travis-ci.org/HumanCellAtlas/data-store/builds/333868556#L2654:

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/bin/domovoi", line 229, in <module>
    awslambda.create_alias(**alias_args)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceConflictException: An error occurred (ResourceConflictException) when calling the CreateAlias operation: Alias already exists: arn:aws:lambda:us-east-1:861229788715:function:dss-visitation-staging:domovoi-stepfunctions-task-Initialize11
```

**Comment by hannes-ucsc** [comment]
Another one:

https://travis-ci.org/HumanCellAtlas/data-store/builds/337032489#L3112

**Comment by hannes-ucsc** [comment]
https://travis-ci.org/HumanCellAtlas/data-store/builds/339134624#L2702

**Comment by kozbo** [comment]
@hannes-ucsc is this still an issue?

**Comment by hannes-ucsc** [comment]
I don't know. I stopped following DSS builds closely after I started working more on Orange.

**Comment by mweiden** [comment]
We haven't seen this issue in a while. @Bento007 believes that we have fixed it. Closing for now. Will reopen if the problem recurs.
