### ISSUE TITLE
S3's eventual consistency causes occasional race in tombstone tests

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#956]
The tombstone tests delete the tombstone during tear-down. A subsequent tombstone test (there are four overall) will recreate the tombstone. This PUT-DELETE-PUT sequence will cause a subsequent GET or HEAD to be only eventually consistent, i.e. its possible that the last PUT may not yet be visible at the time of the GET or HEAD.

The deletion of the tombstone is necessary because the tombstone would interfere with other tests. Originally each test used a new bundle but a [performance optimization](https://github.com/HumanCellAtlas/data-store/commit/e12a5f7c4b7109151d8d93e38c72d6b7d36ce766) changed that to reuse the same bundle for each test.

The solution might be to reset the bundle cache between tombstone tests or something to that effect.

```
6100 ERROR:dss.events.handlers.index:Exception occurred while processing Replica.aws event: {
6100     "Records": [
6100         {
6100             "eventVersion": "2.0",
6100             "eventSource": "aws:s3",
6100             "awsRegion": "us-east-1",
6100             "eventTime": "1970-01-01T00:00:00.000Z",
6100             "eventName": "ObjectCreated:Put",
6100             "userIdentity": {
6100                 "principalId": "AIDAJDPLRKLG7UEXAMPLE"
6100             },
6100             "requestParameters": {
6100                 "sourceIPAddress": "127.0.0.1"
6100             },
6100             "responseElements": {
6100                 "x-amz-request-id": "C3D13FE58DE4C810",
6100                 "x-amz-id-2": "FMyUVURIY8/IgAtTv8xRjskZQpcIZ9KG4V5Wp6S7S/JRWeUWerMUE5JgHvANOjpD"
6100             },
6100             "s3": {
6100                 "s3SchemaVersion": "1.0",
6100                 "configurationId": "testConfigRule",
6100                 "bucket": {
6100                     "name": "org-humancellatlas-dss-test",
6100                     "ownerIdentity": {
6100                         "principalId": "A3NL1KOZZKExample"
6100                     },
6100                     "arn": "arn:aws:s3:::testBucket"
6100                 },
6100                 "object": {
6100                     "key": "bundles/3547f9a8-8cf0-4a29-ad42-b5523f0ed746.2018-02-07T025832.539094Z.dead",
6100                     "size": 45,
6100                     "eTag": "d41d8cd98f00b204e9800998ecf8427e",
6100                     "versionId": "096fKKXTRTtl3on89fVO.nfljtsv6qko",
6100                     "sequencer": "0055AED6DCD90281E5"
6100                 }
6100             }
6100         }
6100     ]
6100 }
6100 Traceback (most recent call last):
6100   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/cloud_blobstore/s3.py", line 181, in get
6100     Key=key
6100   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
6100     return self._make_api_call(operation_name, kwargs)
6100   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
6100     raise error_class(parsed_response, operation_name)
6100 botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
6100 
6100 During handling of the above exception, another exception occurred:
6100 
6100 Traceback (most recent call last):
6100   File "/home/travis/build/HumanCellAtlas/data-store/dss/events/handlers/index.py", line 36, in process_new_indexable_object
6100     self.index_object(key)
6100   File "/home/travis/build/HumanCellAtlas/data-store/dss/util/retry.py", line 207, in wrapper
6100     return f(*args, **kwargs)
6100   File "/home/travis/build/HumanCellAtlas/data-store/dss/events/handlers/index.py", line 52, in index_object
6100     self._index_tombstone(self.replica, identifier)
6100   File "/home/travis/build/HumanCellAtlas/data-store/dss/events/handlers/index.py", line 73, in _index_tombstone
6100     doc = BundleTombstoneDocument.from_replica(replica, tombstone_id)
6100   File "/home/travis/build/HumanCellAtlas/data-store/dss/storage/index_document.py", line 507, in from_replica
6100     tombstone_data = json.loads(blobstore.get(bucket_name, tombstone_id.to_key()))
6100   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/cloud_blobstore/s3.py", line 186, in get
6100     raise BlobNotFoundError(ex)
6100 cloud_blobstore.BlobNotFoundError: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
6100 ERROR
```

**Comment by mweiden** [comment]
@hannes-ucsc @Bento007 is this still an issue? If so I'll pick it up

**Comment by hannes-ucsc** [comment]
I have not seen this since then. I'm torn if we should try to reproduce it, wait for it to occur again or just fix it speculatively without a reproduction.

**Comment by Bento007** [comment]
@hannes-ucsc have you seen this since. Otherwise we can close the ticket.
